### ISSUE TITLE
招募翻译review人员

### ISSUE THREAD

**Issue by songww** [python/python-docs-zh-cn#1]
为了保证翻译的质量，也本着为读者负责的态度，希望找些英语和国语都比较强的小伙伴们review我们已经翻译过的段落。
如果您对翻译Python官方文档感兴趣，且有较多的时间愿意放到这上面来，欢迎您成为我们的一员。
如果觉得自己英语水平不足以担任reviewer的职位，但又想做成贡献，也欢迎直接报名成为一名翻译员。

想参与的小伙伴可以直接在下面留言，并附上自己在transifex上的用户名。

**Comment by silkriver** [comment]
申请参与review~ 我的transifex用户名是starglow

另外我在这里发了一篇宣传文章 https://www.jianshu.com/p/27d2f02a86e9

**Comment by hzhu212** [comment]
`hzhu212` 报名 review

**Comment by songww** [comment]
@hzhu212 感谢，我给您发了邮件，您查收下。

**Comment by Dumeng** [comment]
> alphanow
wants to join as a reviewer.

**Comment by DanceMoonShadow** [comment]
DanceMoonShadow  报名翻译员

**Comment by import-yuefeng** [comment]
想报名review成员~

**Comment by LazyWolfLin** [comment]
LazyWolfLin 报名翻译

**Comment by xzycn** [comment]
lordran 暂报review:D

**Comment by ListenLove** [comment]
文文武 我也暂报review

**Comment by SLboat** [comment]
Nes.AI_NongXiao 报名翻译者!我们是人工智能农校群,一帮狂热的爱好AI的粉丝.

**Comment by hack-fang** [comment]
kaifang 报名翻译

**Comment by chen-chao** [comment]
报名翻译, 已经加入transifex的队伍里了.

**Comment by persnalaunt** [comment]
至今还是0  review ，管理员还健在？

**Comment by zhsj** [comment]
Hi all,

由于我不能确定大家的翻译水平，所以我目前还没有在 Transifex 的 Reviewer 组中添加任何人。但在 Transifex 上加入中文翻译组的申请都很快通过了。

所有加入了 Transifex 的人都可以提交翻译，或者修正已有的翻译（即审阅工作）。如果没有或不想加入 Transifex，在这个 repo 的 issue 中提出翻译错误，也是一种参与审阅的方式。

感谢大家的参与。

**Comment by silkriver** [comment]
其实进度比我们快的法语和韩语都没有reviewer，日语也只review了千分之三

**Comment by jefferyUstc** [comment]
jefferyustc 申请翻译~谢谢

**Comment by chen-chao** [comment]
Hi，已经加入了翻译组。因为没有使用过transifex，所以暂时还没有开始翻译工作。想咨询几个问题：

1. 直接对每个词条翻译就可以吗？还是需要说明词条分工？
2. 如果可以共同翻译一篇文档，如何统一措辞和风格？
3. 和上一条比较类似，如何统一术语？

jeffery <notifications@github.com> 于 2019年4月3日周三 09:28写道：

**Comment by silkriver** [comment]
我觉得术语表和这个链接看一下就可以开始翻了 https://github.com/python/python-docs-zh-cn/issues/10
transifex界面中会列出文本中出现的术语对照

**Comment by SLboat** [comment]
> Hi all,
> 
> 由于我不能确定大家的翻译水平，所以我目前还没有在 Transifex 的 Reviewer 组中添加任何人。但在 Transifex 上加入中文翻译组的申请都很快通过了。
> 
> 所有加入了 Transifex 的人都可以提交翻译，或者修正已有的翻译（即审阅工作）。如果没有或不想加入 Transifex，在这个 repo 的 issue 中提出翻译错误，也是一种参与审阅的方式。
> 
> 感谢大家的参与。

没有出现在组织里呢....

**Comment by persnalaunt** [comment]
> Hi，已经加入了翻译组。因为没有使用过transifex，所以暂时还没有开始翻译工作。想咨询几个问题： 1. 直接对每个词条翻译就可以吗？还是需要说明词条分工？ 2. 如果可以共同翻译一篇文档，如何统一措辞和风格？ 3. 和上一条比较类似，如何统一术语？.......

就目前的实际情况来看，transifex的web编辑器保存后，其他人马上能看的到，应该不会有重复工作，

没看到分工安排，完全根据自己时间和爱好，单独翻译某一篇、某一个段，甚至是单独的一行或短句也行
我还见过专挑目录翻译的家伙，对，就是（Contents-->内容，然后下面都是空白，没翻 )这样），
不管翻多少都行，积少成多吧，对初学者都是有些许帮助的

翻译的质量是仁者见仁，有的直接机翻就粘贴过来了，有的润色和修改的很好，全看作者自己啦。
组里没有Reviewer ，全靠管理员和其他志愿者复查，估计很难达到100%的覆盖
（似乎缺乏工具，有的资源估计被复核了n次，单句都有十几条建议，有的整篇都没一个）

每天大概会发布2、3次，即使Unreviewed、Untranslated状态 也会更新发布到docs.python.org/zh-cn

管理员很懒的，没有公告和手册都，很多都要靠自己摸索
大家还是要多宣传，实际上还有很多人不知道transifex的这个项目，早期各种零散的翻译没能整合起来真的很可惜

**Comment by xzycn** [comment]
现在没有reviewer啊，那我报名翻译吧。
翻译任务如果能够提供"加锁"就好了，保持数据的一致性就好了。

**Comment by chen-chao** [comment]
尝试翻了一下，感觉比想象中困难，感谢Z大对翻译的修正。

另外，是不是直接push到本项目的3.7分支，和在transifex上提交文件是一样的？

>

**Comment by SLboat** [comment]
大家能不能加入一个slack来协作交流,共同交流进步啊.


From SLboat

**Comment by SLboat** [comment]
https://join.slack.com/t/python-docs-zh-cn/shared_invite/enQtNjAxMjI4NjQxODMwLTdhMTVjZTk4Zjk3ODc4YzM0NzhmNjc5YTc5NGE1MDI2YzVhYTY0MGIyOWM3OTJmNjAwNDU2ZWYzZWMxZWFjMjg

我斗胆建了个项目组


From SLboat

**Comment by zhsj** [comment]
> https://join.slack.com/t/python-docs-zh-cn/shared_invite/enQtNjAxMjI4NjQxODMwLTdhMTVjZTk4Zjk3ODc4YzM0NzhmNjc5YTc5NGE1MDI2YzVhYTY0MGIyOWM3OTJmNjAwNDU2ZWYzZWMxZWFjMjg 我斗胆建了个项目组 From SLboat

FTR: I'll not join.

**Comment by SLboat** [comment]
那我就删了,跟着大家搞吧.


From SLboat

**Comment by bmxbmx3** [comment]
请问python3.7的官方文档的中文翻译是出自本项目吗？看了一些，有的貌似机翻，读起来比较生硬。

**Comment by zhsj** [comment]
> 看了一些，有的貌似机翻，读起来比较生硬。

@bmxbmx3 请新建一个 issue，列出你觉得不合适的翻译，以便我们跟踪。

**Comment by bmxbmx3** [comment]
> > 看了一些，有的貌似机翻，读起来比较生硬。
> 
> @bmxbmx3 请新建一个 issue，列出你觉得不合适的翻译，以便我们跟踪。

我加了你们的transifex，目前还没有同意。另，翻译团队有没有相关的群？

**Comment by SLboat** [comment]
搞了个slack,没人喜欢玩,没人看的上....我觉得这个可以传文件,图片,文字,翻译记录,不专注于闲扯乱聊,没什么可为难的.想不到翻译份子们都比较不习惯互相亲近交流,也许大家都太忙了,就算了...

协调问题,辅助新手,鼓励大家参与,互相切磋进步,本意多棒啊.

**Comment by silkriver** [comment]
有个微信群，我觉得这样公开交流就挺好，围墙花园没什么必要

**Comment by SLboat** [comment]
微信不会吵吵闹闹的吗?QQ群也可以吧.


From SLboat

**Comment by chen-chao** [comment]
我觉得可以开一个issue专门用于勘误和交流翻译就可以了.

**Comment by thautwarm** [comment]
能不能搞成一些人负责分发任务，一些人负责接任务，然后每天定量？

**Comment by jefferyUstc** [comment]
用户名：jefferyustc，一直没接受到邀请

**Comment by zhsj** [comment]
> 用户名：jefferyustc，一直没接受到邀请

@jefferyUstc 我并没有在 Transifex 上看到你的加入申请啊。。也没有这个用户名。。

**Comment by Chyroc** [comment]
求加微信群 -_-

**Comment by iceyasha** [comment]
transifex已经提交申请，用户名：iceyasha

**Comment by 1lin24** [comment]
translater: 1lin24

**Comment by WrRan** [comment]
@songww 你好，我发现了翻译中的一处错误。我的tranfix的用户名为：WrRan，已提交申请。

**Comment by KellyHwong** [comment]
请问翻译文档有一定的原则吗？不可能全部直译吧。

**Comment by thautwarm** [comment]
@KellyHwong  Hey!

**Comment by KellyHwong** [comment]
> Hi all,
> 
> 由于我不能确定大家的翻译水平，所以我目前还没有在 Transifex 的 Reviewer 组中添加任何人。但在 Transifex 上加入中文翻译组的申请都很快通过了。
> 
> 所有加入了 Transifex 的人都可以提交翻译，或者修正已有的翻译（即审阅工作）。如果没有或不想加入 Transifex，在这个 repo 的 issue 中提出翻译错误，也是一种参与审阅的方式。
> 
> 感谢大家的参与。

我觉得热情都是有的，但我们需要一个翻译标准，比如转变为国语表达。在transifex好像没找到这样的translation guide。但是在维基翻译中，翻译规则和原则是很详细的。翻译Python是完完全全的原文翻译嘛？况且官方翻译可读性不大好也有诟病了。

**Comment by zhsj** [comment]
> 我觉得热情都是有的，但我们需要一个翻译标准，比如转变为国语表达。在transifex好像没找到这样的translation guide。但是在维基翻译中，翻译规则和原则是很详细的。翻译Python是完完全全的原文翻译嘛？况且官方翻译可读性不大好也有诟病了。

个人是希望能做到[信达雅](https://zh.wikipedia.org/wiki/%E4%BF%A1%E8%BE%BE%E9%9B%85)。做到这几点比较困难，第一步还是先做到准确翻译原文。

**Comment by KS0508** [comment]
个人暂报review

**Comment by KS0508** [comment]
个人暂报review
transifex用户名Miku0831，已提交申请

**Comment by foxleoly** [comment]
报名翻译和reviewer.
已在transifex申请加入.管理看到麻烦审批一下哈!

**Comment by foxleoly** [comment]
感觉沟通有点不太顺畅,能拉一下微信群么wx:foxleoly

**Comment by 9527q** [comment]
你好，提交成为翻译者的申请了：9527q

**Comment by wangliang1993** [comment]
申请参与review~ 我的transifex用户名是liang wang

**Comment by KS0508** [comment]
请问微信群还可以拉进去吗？

可以的话请发邮件告诉我怎么进群，我邮箱：kevinshao2000@gmail.com

**Comment by songww** [comment]
> kevinshao2000@gmail.com

群二维码已发到邮箱

**Comment by 1lin24** [comment]
同求进群二维码 1lin24@sina.com

**Comment by jaystone776** [comment]
求进群二维码

**Comment by songww** [comment]
> 同求进群二维码 [1lin24@sina.com](mailto:1lin24@sina.com)

群二维码已发到邮箱

**Comment by songww** [comment]
![图片](https://user-images.githubusercontent.com/8115960/103391125-c9cd2b80-4b52-11eb-8821-54fa17cc4abd.png)



> 求进群二维码

**Comment by jefferyUstc** [comment]
申请参与项目 jeffery_cpu@163.com

**Comment by WH-2099** [comment]
求进群二维码，wh2099@outlook.com

**Comment by LiHua-Official** [comment]
transifex用户名 LiHua114

**Comment by BlueGlassBlock** [comment]
请求加入群组，3.12 已经接近 beta 阶段了，3.11 翻译仍然没有办法上线

**Comment by WendaoLee** [comment]
问一下我可以进微信群么👀 transifex id：Wendaolee

邮箱 leewendao@outlook.com

**Comment by BlueGlassBlock** [comment]
> 问一下我可以进微信群么👀 transifex id：Wendaolee
> 
> 邮箱 [leewendao@outlook.com](mailto:leewendao@outlook.com)

已经发送邀请二维码了，请及时查收 :)

**Comment by QY0831** [comment]
报名翻译，transifex用户名：qinyuchen

**Comment by Dumeng** [comment]
Thank everyone for your interest in contributing to the Python docs zh-CN translation program as a reviewer. However, the review process for all Python translation programs is not mandatory. Instead, we encourage everyone to create new translations, report typo issues, or fix translations directly by becoming a translator. So, I'm closing the issue for now.
-----
感谢这里的每个人有兴趣作为reviewer为 Python 文档 zh-CN 翻译项目做出贡献。 然而，在所有Python翻译项目中的审校过程都并非强制性的。相反，我们鼓励每个人通过成为翻译者来创建新的翻译、报告拼写错误或直接修复翻译。所以，我会将这个issue标记为已解决。
