### ISSUE TITLE
Python3 中文文档 time.time() 函数翻译改进建议

### ISSUE THREAD

**Issue by TRHX** [python/python-docs-zh-cn#100]
【目标链接】：https://docs.python.org/zh-cn/3/library/time.html#time.time

【原始英文】：Return the time in seconds since the epoch as a floating point number. The specific date of the epoch and the handling of leap seconds is platform dependent. On Windows and most Unix systems, the epoch is January 1, 1970, 00:00:00 (UTC) and leap seconds are not counted towards the time in seconds since the epoch. This is commonly referred to as Unix time. To find out what the epoch is on a given platform, look at gmtime(0).

【原始翻译】：返回浮点数的 seconds since the epoch 。epoch 的具体日期和 [leap seconds](https://en.wikipedia.org/wiki/Leap_second) 的处理取决于平台。在Windows和大多数Unix系统上， epoch 是1970年1月1日00:00:00（UTC），并且闰秒不计入 seconds since the epoch 。 这通常被称为 [Unix time](https://en.wikipedia.org/wiki/Unix_time) 。 要找出给定平台上的 epoch ，请查看 `gmtime(0)`。

【改进建议】：以秒为单位返回从纪元（epoch）开始的时间作为浮点数。纪元的具体日期和闰秒（[leap seconds](https://en.wikipedia.org/wiki/Leap_second)）的处理取决于平台。在Windows和大多数Unix系统中，纪元是1970年1月1日00:00:00（UTC），并且闰秒不计入自纪元以来以秒为单位的时间。这通常被称为[Unix时间](https://en.wikipedia.org/wiki/Unix_time)。要了解给定平台上的纪元，请查看 `gmtime(0)`。

【改进理由】：翻译不准确，语意不清，部分英文未正确翻译。

**Comment by silkriver** [comment]
fixed
