### ISSUE TITLE
翻译错误：Python 标准库 » 并发执行 » subprocess --- 子进程管理

### ISSUE THREAD

**Issue by t123yh** [python/python-docs-zh-cn#101]
https://docs.python.org/zh-cn/3.8/library/subprocess.html#subprocess.run

原文：When used, the internal Popen object is automatically created with stdin=PIPE, and the stdin argument may not be used as well.

现在的译文：当使用此参数时, **内部的 Popen 对象将自动被创建, 伴随着设置 stdin=PIPE, 并且 stdin 可能不被使用**.

建议修改：当使用此参数时，**在创建内部 Popen 对象时将自动带上 stdin=PIPE，并且不能再手动指定 stdin 参数**。

**Comment by silkriver** [comment]
fixed
