### ISSUE TITLE
Python3 中文文档 deque 对象相关方法翻译改进建议

### ISSUE THREAD

**Issue by TRHX** [python/python-docs-zh-cn#102]
错误一：

【目标链接】：https://docs.python.org/zh-cn/3/library/collections.html#collections.deque.count

【原始英文】：Count the number of deque elements equal to x.

【原始翻译】：计算 deque 中个数等于 x 的元素。

【改进建议】：计算 deque 中元素等于 x 的个数。

【改进理由】：翻译错误。

---

错误二：

【目标链接】：https://docs.python.org/zh-cn/3/library/collections.html#collections.deque.index

【原始英文】：Return the position of x in the deque (at or after index start and before index stop). Returns the first match or raises ValueError if not found.

【原始翻译】：返回第 x 个元素（从 start 开始计算，在 stop 之前）。返回第一个匹配，如果没找到的话，升起 ValueError 。

【改进建议】：返回 x 在 deque 中的位置（在索引 start 之后，索引 stop 之前）。返回第一个匹配项，如果未找到则引发 ValueError。

【改进理由】：翻译错误。

---

其他错误：

在后面的 insert(i, x)、pop()、popleft()、remove(value) 方法中，引发某个错误，均错误翻译为升起某个错误。

![](https://i.loli.net/2020/02/29/PIRWBqKYGJcDhnw.png)

**Comment by silkriver** [comment]
fixed
