### ISSUE TITLE
python3中文文档 multiprocessing 翻译改进建议

### ISSUE THREAD

**Issue by VistaQvQ** [python/python-docs-zh-cn#104]
【目标链接】：https://docs.python.org/zh-cn/3.7/library/multiprocessing.html

【原始英文】：Generally **synchronization primitives** are not as necessary in a multiprocess program as they are in a multithreaded program.

【原始翻译】：通常来说同步愿意在多进程环境中并不像它们在多线程环境中那么必要。

【改进建议】：通常来说同步原语在多进程环境中并不像它们在多线程环境中那么必要。

【改进理由】：翻译错误。

**Comment by silkriver** [comment]
fixed
