### ISSUE TITLE
错别字: 3.7: subprocess: '然后返回一个 CompletedProcess *示例*'

### ISSUE THREAD

**Issue by Denis-Oakley** [python/python-docs-zh-cn#106]
https://docs.python.org/zh-cn/3.7/library/subprocess.html#subprocess.run

> 运行被 arg 描述的指令。等待指令完成，然后返回一个 CompletedProcess **示例**。

应该为:
运行被 arg 描述的指令。等待指令完成，然后返回一个 CompletedProcess **实例**。

**Comment by silkriver** [comment]
fixed
