### ISSUE TITLE
建议将“课前甜点”更改为“激发学习的兴趣”

### ISSUE THREAD

**Issue by qiuhuachuan** [python/python-docs-zh-cn#108]
whet your appetite, whet可以翻译为刺激、激发，appetite可以翻译为食欲、渴求、欲望；整个短语可以理解为激发你的某种欲望、某种渴求，而这里是作为教程，对知识的渴求，建议翻译为“激发学习的兴趣”。

参考了这个网站的词典解释：https://www.yourdictionary.com/appetite

**Comment by zhsj** [comment]
翻译并不需要逐字按原文翻译的。。

“课前甜点”这个翻译，我印象中存在已久了，感觉挺好的。

**Comment by Dumeng** [comment]
开胃前菜

**Comment by fdx666666** [comment]
课前甜点, 确实不符合中国人的用语习惯.
