### ISSUE TITLE
Python 3.8.2 中文文档turtle模块Screen方法ontimer参数建议

### ISSUE THREAD

**Issue by myfix16** [python/python-docs-zh-cn#109]
该方法第一个参数fun可以是一个带参数函数

**Comment by zhsj** [comment]
我想你说的是这个函数？
https://docs.python.org/3/library/turtle.html#turtle.ontimer

没使用过这个库，但目前英文原文和代码里的注释都是说 fun 是无参数的。

https://github.com/python/cpython/blob/c606624af8d4cb3b4a052fb263bb983b3f87585b/Lib/turtle.py#L1440-L1459

**Comment by myfix16** [comment]
你好，
经过再次测试和对源码的研究，我发现fun带参数传入会出现问题，因此fun应该是不带参数的。
感谢你的及时回复，对带来的不便深表歉意。

Best regards

发件人: zhsj<mailto:notifications@github.com>
发送时间: 2020年4月18日 20:11
收件人: python/python-docs-zh-cn<mailto:python-docs-zh-cn@noreply.github.com>
抄送: myfix16<mailto:myfix16@Outlook.com>; Author<mailto:author@noreply.github.com>
主题: Re: [python/python-docs-zh-cn] Python 3.8.2 中文文档turtle模块Screen方法ontimer参数建议 (#109)


我想你说的是这个函数？
https://docs.python.org/3/library/turtle.html#turtle.ontimer

没使用过这个库，但目前英文原文和代码里的注释都是说 fun 是无参数的。

https://github.com/python/cpython/blob/c606624af8d4cb3b4a052fb263bb983b3f87585b/Lib/turtle.py#L1440-L1459

―
