### ISSUE TITLE
Bug report from the @docs mailing list.

### ISSUE THREAD

**Issue by JulienPalard** [python/python-docs-zh-cn#11]
https://mail.python.org/pipermail/docs/2018-December/038721.html transcribed for convinience:

> Hi, I find a mistake on https://docs.python.org/zh-cn/3.7/bugs.html, maybe
it is because the translation.
In the forth paragraph, "解决方案是使用 Python 的原始字符串表示法来表达正则样式；在以 'r' 为前缀的字符串文本中,
反斜杠没有任何转义。 因此,``r"n"`` 是一个包含 '\' 和 'n' 的双字符字符串, 而 "\n" 是包含换行符的一个字符字符串。
我们一般用原始表示法来表达样式。" while the original express is " So r"\n" is a
two-character string containing".
There is a missing "\" and should be "r"\n"".
Thank you!
Best Wishes,
Bruce Wang

**Comment by silkriver** [comment]
It's caused by missing a space char, I just fixed this error.
https://www.transifex.com/python-doc/python-newest/translate/#zh_CN/library--re/108410899
https://docs.python.org/zh-cn/3.7/library/re.html
