### ISSUE TITLE
又报错了

### ISSUE THREAD

**Issue by silkriver** [python/python-docs-zh-cn#110]
说近两个月没改动过的 whatsnew/2.7 有问题，不知道是什么情况

**Comment by zhsj** [comment]
是翻译的问题

![image](https://user-images.githubusercontent.com/227180/79749057-15cb9d80-8341-11ea-9449-75e29ed74bcb.png)

应该是

```
 `Python 包用户指南 <https://packaging.python.org>`__ 
```

在url前面少了个空格。
