### ISSUE TITLE
函数和结构期望中从获取连续的项直到所提供的项全部耗尽。

### ISSUE THREAD

**Issue by MisterZeng** [python/python-docs-zh-cn#112]
我们称这样对象为 iterable，也就是说，适合作为这样的目标对象：函数和结构期望中从获取连续的项直到所提供的项全部耗尽。 我们已经看到 for 语句就是这样一种结构，而接受可迭代对象的函数的一个例子是 sum():

应当改为：
我们称这样对象为 iterable，也就是说，适合作为这样的目标对象：函数和结构期望从中获取连续的项直到所提供的项全部耗尽。 我们已经看到 for 语句就是这样一种结构，而接受可迭代对象的函数的一个例子是 sum():

**Comment by MisterZeng** [comment]
4.3. range() 函数¶

**Comment by silkriver** [comment]
fixed
