### ISSUE TITLE
翻译错误：Python 标准库 » 数字和数学模块 »statistics ，mode应翻译为众数，不是模式

### ISSUE THREAD

**Issue by xyzhou-1** [python/python-docs-zh-cn#116]
中文文档链接：https://docs.python.org/zh-cn/3/library/statistics.html

错误翻译：**根据**离散或标称的 data 返回单个**最觉**的数据点。此**模式**（如果存在）是最典型的值，并可用来度量中心的位置。

英文：Return the single **most common** data point **from** discrete or nominal data. The **mode** (when it exists) is the most typical value and serves as a measure of central location.

错误点：
1. from应翻译为`从`而不是`根据`
2. `最觉`翻译错误，应为`出现最多`
3. 所有的`mode`都翻译成了模式，应改为`众数`，**这里只列出一处，全文共有10处错误**，使用 `ctrl+f` 检索 ”模式“即可

>有一个翻译成了单模，检索不会显示，应翻译为“单个众数”（single mode)，直接翻译为众数感觉也行。“最常见的”应翻译为，“出现最多的”（most common value）
![image](https://user-images.githubusercontent.com/47747466/82522233-6bbb7d00-9b5b-11ea-8ff9-54c0349be6ec.png)

**Comment by silkriver** [comment]
fixed
