### ISSUE TITLE
Python3.8.3中文文档math.perm(n, k=None)翻译错误

### ISSUE THREAD

**Issue by dongchenxu93** [python/python-docs-zh-cn#119]
链接：https://docs.python.org/3/library/math.html
英文原文：Return the number of ways to choose k items from n items without repetition and **with order**.
中文翻译：返回不重复且**无顺序**地从 n 项中选择 k 项的方式总数。

正确中文翻译：返回不重复且**有顺序**地从 n 项中选择 k 项的方式总数。

**Comment by silkriver** [comment]
fixed

**Comment by dongchenxu93** [comment]
Just checked and have not been fixed or worked.

**Comment by silkriver** [comment]
fixed on transifex.com, sync to github.com then update to python.org just may need hours.
