### ISSUE TITLE
3.8 json 模块 typo

### ISSUE THREAD

**Issue by GeekDuanLian** [python/python-docs-zh-cn#125]
https://docs.python.org/zh-cn/3/library/json.html

注解 这个模块的编码器和解码器默认保护输入和输出的顺序。仅当底层的容器未 _**拍序**_ 时才会失去顺序。
注解 这个模块的编码器和解码器默认保护输入和输出的顺序。仅当底层的容器未 _**排序**_ 时才会失去顺序。

顺便，我提交了 Transifex 翻译者的申请，觉得这种小错误自己上去修一下就行了，没必要还发个 issue
希望能通过一下，相同用户名的

**Comment by silkriver** [comment]
fixed
