### ISSUE TITLE
Python 教程 4.7.5. 解包参数列表

### ISSUE THREAD

**Issue by fishkylin** [python/python-docs-zh-cn#126]
链接: https://docs.python.org/zh-cn/3/tutorial/controlflow.html#unpacking-argument-lists
原句: 可以使用 *-操作符 来编写函数调用以便从列表或元组中解包参数
建议: 可以使用 * 操作符 来编写函数调用以便从列表或元组中解包参数
原因: 容易引起歧义

**Comment by silkriver** [comment]
fixed
