### ISSUE TITLE
中文翻译的没有逻辑性

### ISSUE THREAD

**Issue by tenlives** [python/python-docs-zh-cn#127]
https://docs.python.org/zh-cn/3/library/argparse.html ，我看了这篇，感觉这是一种不负责任的翻译，没有逻辑性的概念，给了每一段代码后只是简单几句话概括，并没有对代码进行注释，是一种敷衍的行为，请更正学术不严谨的行为

**Comment by zhsj** [comment]
请问和原文比较呢？我们 **不会创作新的内容**，我们只是将原文翻译为中文。如果觉得需要对代码进行注释，请用 **英文** 在https://bugs.python.org/ 对 **英文原文** 进行反馈。

**Comment by silkriver** [comment]
其实代码根本就不在文档的po文件中，里面即使带注释我们也是无法去翻译的。
