### ISSUE TITLE
当有多个历史版本时，显示的不是最新的那个版本而是最早的版本

### ISSUE THREAD

**Issue by LiTianxiong** [python/python-docs-zh-cn#13]
当我多次提交了某个条目的翻译时，显示的是最早的那个版本。
例如：[壁垒对象](https://docs.python.org/zh-cn/3/library/threading.html#barrier-objects) 中的第一段话（在Transifex中的位置是[这里](https://www.transifex.com/python-doc/python-36/translate/#zh_CN/library--threading/147269801)）

**Comment by zhsj** [comment]
翻译不是实时显示在官网上的，有一定延迟。

**Comment by silkriver** [comment]
可以再修改一次试试

**Comment by LiTianxiong** [comment]
@zhsj 看了GitHub上的commit记录，commit的时候我已经提交了最新的翻译，但还是commit的第一个版本。

**Comment by silkriver** [comment]
我找到原因了，你用的位置是 3.6 版的，3.6 版已经归档不能再修改，应该改 newest 版
