### ISSUE TITLE
Python3.8-3.10中文文档修正：concurrent.futures.ThreadPoolExecutor的翻译

### ISSUE THREAD

**Issue by GalaxySnail** [python/python-docs-zh-cn#130]
地址：[concurrent.futures.ThreadPoolExecutor 在3.8版更改](https://docs.python.org/zh-cn/3/library/concurrent.futures.html?highlight=gil#concurrent.futures.ThreadPoolExecutor)

其[英文原文](https://docs.python.org/3/library/concurrent.futures.html?highlight=gil#concurrent.futures.ThreadPoolExecutor)是：

```
It utilizes at most 32 CPU cores for CPU bound tasks which release the GIL. And it avoids using very large resources implicitly on many-core machines.
```

目前翻译是：

```
它会使用至多32个CPU核心用于CPU密集型任务并将释放 GIL。它还会避免在多核机器上隐式地使用非常大量的资源。
```

**建议改成：**

```
对于那些释放了GIL的CPU密集型任务，它最多会使用32个CPU核心。这样能够避免在多核机器上隐式地使用非常大量的资源。
```

这个关于GIL的翻译问题十分严重，可能会对读者造成误导，请尽快修复。

**Comment by GalaxySnail** [comment]
另外，这里的`GIL`可以添加一个[到术语对照表的链接](https://docs.python.org/zh-cn/3/glossary.html#term-gil)

**Comment by SeanChao** [comment]
已经修正啦，感谢指出
