### ISSUE TITLE
Python3 中文文档“Curses 编程”中的错别字

### ISSUE THREAD

**Issue by AirManH** [python/python-docs-zh-cn#134]
## 地址

[https://docs.python.org/zh-cn/3/howto/curses.html#windows-and-pads](https://docs.python.org/zh-cn/3/howto/curses.html#windows-and-pads)

## 原内容

> 函数 initscr() 返回的 stdscr 对象覆盖整个屏幕。许多程序可能只需要这一个窗口，但你可能希望把屏幕分割为多个更小的窗口，来分别重绘或者清楚它们

## 截图

![screenshot](https://user-images.githubusercontent.com/30146150/90382793-d07e6900-e0b1-11ea-944d-045b25fb5a9e.png)

## 更正建议

应该将“重绘或者**清楚**它们”更改为“重绘或者**清除**它们”

**Comment by silkriver** [comment]
fixed
