### ISSUE TITLE
Console problem

### ISSUE THREAD

**Issue by twoone-3** [python/python-docs-zh-cn#136]
![Screenshot_2020_0828_104656](https://user-images.githubusercontent.com/62778573/91515469-d4b14e80-e91b-11ea-8345-99735a9bf1f4.png)
When I use the Py_Initialize function in cpython, the console is forced to become gbk encoding, hoping to be compatible with UTF-8

**Comment by twoone-3** [comment]
能用中文写啊...害得我还翻译成英文

**Comment by zhsj** [comment]
你好，我的理解是你想说Py_Initialize函数有bug？而不是cpython文档翻译有问题？

如果是Py_Initialize函数本身的bug的话，请在 https://bugs.python.org/ 报告，这上面是需要用英文的。

这里是负责维护文档中文翻译的，暂时没有能力修复cpython本身的bug。

**Comment by twoone-3** [comment]
好的,感谢
