### ISSUE TITLE
python3中文文档改进建议

### ISSUE THREAD

**Issue by vzpd** [python/python-docs-zh-cn#137]
目标链接：https://docs.python.org/zh-cn/3.7/library/asyncio-task.html

目标位置：Documentation » Python 标准库 » 网络和进程间通信 » asyncio --- 异步 I/O »基于生成器的协程

问题语句：此装饰器 已弃用 并计划觉得 Python 3.10 中移除。

存在问题：翻译不通顺

改进建议：此装饰器 已弃用 并计划在Python 3.10 中移除。

**Comment by silkriver** [comment]
fixed
