### ISSUE TITLE
勘误？

### ISSUE THREAD

**Issue by wi24rd** [python/python-docs-zh-cn#14]
https://docs.python.org/zh-cn/3/reference/datamodel.html 里：
numbers.Real (float)
    此类对象表示机器级的双精度浮点数。其所接受的取值范围和溢出处理将受制于底层的机器架构 (以及 C 或 Java 实现)。Python 不支持单精度浮点数；支持后者通常的理由是节省处理器和内存消耗，**但这会妨碍在 Python 中使用对象**，因此没有理由包含两种浮点数而令该语言变得复杂。
原文：
Python does not support single-precision floating point numbers; the savings in processor and memory usage that are usually the reason for using these are dwarfed by the overhead of using objects in Python, so there is no reason to complicate the language with two kinds of floating point numbers.
原文要表达的意思应该是说使用单精度浮点数节省的消耗相对于对象的使用来说微不足道所以Python没有部署单精度？

**Comment by silkriver** [comment]
谢谢指出，应该是这意思，我来改一下
