### ISSUE TITLE
Pyhton 教程 9. 类 翻译改进

### ISSUE THREAD

**Issue by jckling** [python/python-docs-zh-cn#144]
- [9.1. 名称和对象](https://docs.python.org/zh-cn/3/tutorial/classes.html#a-word-about-names-and-objects)

> 但是，别名对涉及可变对象，如列表，字典和大多数其他类型，的Python代码的语义可能会产生惊人的影响。这通常用于程序的好处，因为别名在某些方面表现得像指针。

但是，别名对涉及可变对象（如列表，字典和大多数其他类型）的 Python 代码的语义可能会产生惊人的影响。通常这样做是为了使程序受益，因为别名在某些方面表现得像指针。

> 例如，传递一个对象很便宜，因为实现只传递一个指针；

例如，传递一个对象的代价很小，因为实现只传递一个指针；

- [9.2. Python 作用域和命名空间](https://docs.python.org/zh-cn/3/tutorial/classes.html#python-scopes-and-namespaces)

> 在执行期间的任何时刻，会有 3 或 4 个个命名空间可被直接访问的嵌套作用域:

在执行期间的任何时刻，会有 3 或 4 ~~个~~个命名空间可被直接访问的嵌套作用域：
.............................................................................................................................................................^

- [9.10. 生成器表达式](https://docs.python.org/zh-cn/3/tutorial/classes.html#generator-expressions)

> 所用语法类似列表推导式，将外层为圆括号而非方括号。

所用语法类似列表推导式，但外层为圆括号而非方括号。

---

PS：本章中许多处 **Python** 的左右两侧没有空格

**Comment by silkriver** [comment]
fixed
