### ISSUE TITLE
Pyhton 教程 11. 标准库简介 —— 第二部分 翻译改进

### ISSUE THREAD

**Issue by jckling** [python/python-docs-zh-cn#145]
- [11.2. 模板](https://docs.python.org/zh-cn/3/tutorial/stdlib2.html#templating)

> Template 的子类可以自定义定界符。

Template 的子类可以自定义**分隔**符。

<br>

- [11.3. 使用二进制数据记录格式](https://docs.python.org/zh-cn/3/tutorial/stdlib2.html#working-with-binary-data-record-layouts)

> `"<"` 代表它们是标准尺寸的小尾型字节序

`"<"` 代表它们是标准尺寸的**小端**字节序

<br>

- [11.4. 多线程](https://docs.python.org/zh-cn/3/tutorial/stdlib2.html#multi-threading)

> 实现多任务协作的首选方法是将对资源的所有请求集中到一个线程中

实现多任务协作的首选方法是将**所有对资源的请求**集中到一个线程中

<br>

- [11.7. 用于操作列表的工具](https://docs.python.org/zh-cn/3/tutorial/stdlib2.html#tools-for-working-with-lists)

> 例如 bisect 模块具有用于操作排序列表的函数:

例如 bisect 模块具有用于操作**有序**列表的函数：
.............................................................................................^

**Comment by silkriver** [comment]
fixed
