### ISSUE TITLE
concurrent.futures模块勘误及建议

### ISSUE THREAD

**Issue by pjshu** [python/python-docs-zh-cn#146]
https://docs.python.org/zh-cn/3/library/concurrent.futures.html

## 勘误

**原文**

> 类似于 map(func, *iterables) 除去：
> 应立即收集 iterables 不要延迟再收集;
> func 是异步执行的以及对 func 的调用可以同时执行。

**修改为:**

方法类似于map函数,除了以下两点:
可迭代对象是立即执行的而不是延迟执行的；
func是异步执行的，对func的多个调用可能并发执行。

**理由**

文档想表达的意思时,当调用Executor.map函数后,map函数内的函数被立即执行,而不是像内建map一样延迟执行,比如

```
def task(_):
    t = random.randint(1, 10)
    time.sleep(t)
    print(t, 'finish')


with ThreadPoolExecutor(max_workers=5) as executor:
    res = executor.map(task, (_ for _ in range(8)))
    time.sleep(10)#这条语句之前,task函数就已经被调用执行,而内置map函数迭代时才执行


```
## 建议

> 当待执行的期程完成执行后向执行者发送信号

建议future翻译为future对象或者不翻译,而不是期程

**Comment by pjshu** [comment]
以及re模块勘误 
https://docs.python.org/zh-cn/3/library/re.html

**翻译**
> $: 匹配字符串尾或者换行符的前一个字符

**原文**
> Matches the end of the string or just before the newline at the end of the string

**建议修改**
> 匹配字符串尾 或者在 字符串尾的换行符的前一个字符

**理由**

```
# 1
re.findall(r'test$','test\n')
# ['test']

# 2
re.findall(r'test$','test')
# ['test']

# 3
re.findall(r'test$11','test\n')
# []
```
第三种情况是不会匹配的, 
原文表述的是, 匹配字符串尾(2)或者字符串尾的换行符前的字符(1)

**Comment by silkriver** [comment]
fixed
