### ISSUE TITLE
“常见问题”章节中的翻译错误

### ISSUE THREAD

**Issue by Ranlajetech** [python/python-docs-zh-cn#147]
目标链接：https://docs.python.org/zh-cn/3.8/faq/windows.html#how-do-i-run-a-python-program-under-windows

目标位置：该节倒数第三段

原始英文：You may also find that you have a Start-menu entry such as Start ‣ Programs ‣ Python 3.x ‣ Python (command line) that results in you seeing the >>> prompt in a new window. 

原始译文：你可能发现在开始菜单有一个这样的选项 开始 ‣ 所有程序 ‣ Python 3.x ‣ Python (command line) ， 运行它后会出现一个有着 >>> 提示的想不出来口。

Bug描述：‘prompt’ 翻译错误。

**Comment by silkriver** [comment]
fixed
