### ISSUE TITLE
翻译错误

### ISSUE THREAD

**Issue by JarHMJ** [python/python-docs-zh-cn#15]
[https://docs.python.org/zh-cn/3.7/library/collections.html?highlight=namedtuple#collections.namedtuple](https://docs.python.org/zh-cn/3.7/library/collections.html?highlight=namedtuple#collections.namedtuple)里：
class collections.OrderedDict([items])中move_to_end(key, last=True)
移动存在的 key 到有序字典的首末。_**如果 last 为真，就移动到首位，否则就到末尾。**_如果 key 不存在，就升起 KeyError。
翻译有误，正确应该是_**如果 last 为真，就移动到末尾，否则就到首位。**_

**Comment by silkriver** [comment]
谢谢指出

**Comment by Dumeng** [comment]
Fixed @zhsj

**Comment by cIark** [comment]
https://docs.python.org/zh-cn/3.7/tutorial/introduction.html
等号（=）用于给一个变量赋值。然后在喜爱个交互命令之前不会有结果显示出来:
喜爱个？是下一个么？

**Comment by cIark** [comment]
https://docs.python.org/zh-cn/3.7/tutorial/introduction.html
等号（=）用于给一个变量赋值。然后在喜爱个交互命令之前不会有结果显示出来:
喜爱个？是下一个么？

**Comment by silkriver** [comment]
> https://docs.python.org/zh-cn/3.7/tutorial/introduction.html
> 等号（=）用于给一个变量赋值。然后在喜爱个交互命令之前不会有结果显示出来:
> 喜爱个？是下一个么？

谢谢，Fixed

**Comment by YanHuaSuiMei** [comment]
错误翻译(原文倒数第二段):[由三个点号分隔的两个本义字符表示在指定 (开) 区间范围内的任意单个 ASCII 字符](https://docs.python.org/zh-cn/3/reference/introduction.html)

原文内容:[Two literal characters separated by three dots mean a choice of any single character in the given (inclusive) range of ASCII characters](https://docs.python.org/3/reference/introduction.html)

**inclusive**:  包含全部费用;包括所提到的费用在内;包括提到的所有的天数(或月、数目等)在内;包容广阔的;范围广泛的

所以我觉得应该是闭区间, 而且原文范式中也很明确...

最后感谢翻译文档的大佬, 真的对我这个边看英文边谷歌翻译的的很有帮助.
