### ISSUE TITLE
3.9.0Tuturial中文文档2.1.1的翻译问题

### ISSUE THREAD

**Issue by iamfangyun** [python/python-docs-zh-cn#153]
英文原文：When the script name is given as '-' (meaning standard input), sys.argv[0] is set to '-'.

中文版：如果脚本名是标准输入，sys.argv[0] 就是 '-'。

建议修改为：如果脚本名是单纯的'-'(标准输入)，sys.argv[0] 就是 '-'。

**Comment by silkriver** [comment]
fixed
