### ISSUE TITLE
A typo in statistics library

### ISSUE THREAD

**Issue by rickygao** [python/python-docs-zh-cn#154]
自 `3.8` 起，`statistics` 被翻译，如：[statistics](https://docs.python.org/zh-cn/3.8/library/statistics.html).

第二段

> 此模块并不是诸如 NumPy ， SciPy 等第三方库或者诸如 Minitab ， SAS ， Matlab 等针对专业统计学家的专有全功能统计软件包的竟品。此模块针对图形和科学计算器的水平。

中，「竟品」应当为「竞品」。

**Comment by silkriver** [comment]
fixed
