### ISSUE TITLE
Python3中文文档改进建议：threading库

### ISSUE THREAD

**Issue by The-Earth** [python/python-docs-zh-cn#159]
- 链接：https://docs.python.org/zh-cn/3/library/threading.html#threading.enumerate
- 位置：threading.active_count() 节
- 原文：Return the number of Thread objects currently alive. The returned count is equal to the length of the list returned by enumerate().
- 现译文：返回当前存活的线程类 Thread 对象。返回的计数等于 enumerate() 返回的列表长度。
- 建议译文：返回当前存活的 Thread 对象的数量。返回值与 enumerate() 所返回的列表长度一致。
- 备注：第一句里的 the number of 没有被翻译出来（也和 active_count 实际返回的东西不符）；第二句做了修饰。

**Comment by silkriver** [comment]
fixed
