### ISSUE TITLE
A tiny error

### ISSUE THREAD

**Issue by rickygao** [python/python-docs-zh-cn#160]
[weakref](https://docs.python.org/zh-cn/3/library/weakref.html) 中第六段最后多了反引号。

**Comment by rickygao** [comment]
[builtins](https://docs.python.org/zh-cn/3/library/builtins.html) 中第三段的 `__builtins__` 没有正确地被反引号包裹成代码块。

**Comment by rickygao** [comment]
[builtins](https://docs.python.org/zh-cn/3/library/builtins.html) 中第三段的 `__builts__` 没有正确地被反引号包裹成代码块。

**Comment by silkriver** [comment]
fixed
