### ISSUE TITLE
json --- JSON 编码和解码器一节json.dump中indent参数介绍里反引号包裹问题

### ISSUE THREAD

**Issue by jiangzhuochi** [python/python-docs-zh-cn#161]
网址：
[json --- JSON编码和解码器](https://docs.python.org/zh-cn/3/library/json.html?highlight=json%20dump#json.dump)

有问题的部分：
如果 indent 是一个非负整数或者字符串，那么 JSON 数组元素和对象成员会被美化输出为该值指定的缩进等级。如果缩进等级为零、负数或者 ""，则只会添加换行符。None``（默认值）选择最紧凑的表达。使用一个正整数会让每一层缩进同样数量的空格。如果 *indent* 是一个字符串（比如 ``"\t"），那个字符串会被用于缩进每一层。

修正：反引号只包裹 `None` 和 `"\t"`，错误的包裹导致了 *indent* 也没正确显示斜体

**Comment by silkriver** [comment]
fixed
