### ISSUE TITLE
Copy 的内容在 Transifex 里翻译了，但是官档没有显示中文

### ISSUE THREAD

**Issue by jaystone776** [python/python-docs-zh-cn#162]
https://docs.python.org/zh-cn/3/library/copy.html 里有一句 “The deepcopy() function avoids these problems by:”，这句话在 Transifex 中， joshoy 两年前已经翻译了，但官网显示的还是英文。我以为是没有生效，今天试着修改了一下，但是还是没有更新，不知道是因为什么，还请查看一下

**Comment by WH-2099** [comment]
:func:`deepcopy` 中间不能夹有空格，之前的翻译中间误插了一个空格，可能导致官方库 test 出错然后被剔除出来了

**Comment by jaystone776** [comment]
了然，多谢，我去改下
