### ISSUE TITLE
Python greater number game

### ISSUE THREAD

**Issue by YashDhankhar** [python/python-docs-zh-cn#163]
x = input("Your first number: ")
y = input("Your second number: ")

if (y < x):
    print(x + " is greater than " + y)
else:
    print(y + " is greater than " + x)

# is this correct?  please tell me what's the issue in this code

**Comment by zhsj** [comment]
Sorry I don't understand your question. Please note that this place is only for Chinese translation issue of https://docs.python.org/zh-cn
