### ISSUE TITLE
文档中 内置类型 中的错别字问题

### ISSUE THREAD

**Issue by WANGJUNHAOmatt** [python/python-docs-zh-cn#165]
1.  [```str.count(sub[, start[, end]])```](https://docs.python.org/zh-cn/3/library/stdtypes.html#str.count) 中 应为 **返回** 而不是 **反回**
> 反回子字符串```sub```在 ```[start, end]```范围内非重叠出现的次数。 可选参数 `start` 与 `end `会被解读为切片表示法。

2. [`bytes.ljust(width[, fillbyte])`](https://docs.python.org/zh-cn/3/library/stdtypes.html#bytes.ljust) 同理

**Comment by silkriver** [comment]
fixed
