### ISSUE TITLE
《concurrent.futures --- 启动并行任务》有地方翻译疏忽了

### ISSUE THREAD

**Issue by Ercilan** [python/python-docs-zh-cn#167]
在 Executor 对象的：
--- 
shutdown(wait=True, *, cancel_futures=False)

    当待执行的 future 对象完成执行后向执行者发送信号，它就会释放正在使用的任何资源。 在关闭后调用 Executor.submit() 和 Executor.submit() 会触发 RuntimeError。
---
应该一个是Executor.map()

**Comment by silkriver** [comment]
fixed
