### ISSUE TITLE
导入系统, 漏字

### ISSUE THREAD

**Issue by lau-jay** [python/python-docs-zh-cn#168]
https://docs.python.org/zh-cn/3/reference/import.html#importsystem
原译文:所有模块都有自己的名字。 子包名与其父包名以点号分隔，与 Python 的标准属性访问语法致
应该是: 所有模块都有自己的名字。 子包名与其父包名以点号分隔，与 Python 的标准属性访问语法一致

**Comment by silkriver** [comment]
fixed
