### ISSUE TITLE
错字: `asyncio->事件循环->传输文件` 一节

### ISSUE THREAD

**Issue by jlshix** [python/python-docs-zh-cn#170]
https://docs.python.org/zh-cn/3/library/asyncio-eventloop.html#transferring-files

如上链接, 在 `asyncio->事件循环->传输文件` 一节:

`如果可用的化，该方法将使用高性能的 os.sendfile() 。`

应改为

`如果可用的话，该方法将使用高性能的 os.sendfile() 。`

**Comment by silkriver** [comment]
fixed
