### ISSUE TITLE
`numbers` 模块翻译错误

### ISSUE THREAD

**Issue by rickygao** [python/python-docs-zh-cn#171]
1. [numbers.Rational](https://docs.python.org/zh-cn/3/library/numbers.html#numbers.Rational.numerator) `numerator` 和 `denominator` 应与前文一样翻译为“抽象的”；
2. [numbers 加入更多数字的ABC](https://docs.python.org/zh-cn/3/library/numbers.html#adding-more-numeric-abcs) 行内代码块 `MyFoo` 包裹错误；
3. [实现算术运算](https://docs.python.org/zh-cn/3/library/numbers.html#implementing-the-arithmetic-operations) 应为「算术」而非「算数」。有序列表

   ```
   1. 如果 A 被定义成一个承认``b`` 的 __add__()，一切都没有问题。
   ```

   中行内代码块 `b` 包裹错误。

**Comment by silkriver** [comment]
fixed

**Comment by rickygao** [comment]
[numbers.Numberr](https://docs.python.org/zh-cn/3/library/numbers.html#numbers.Number) 这里也有代码块包裹错误。

**Comment by silkriver** [comment]
fixed
