### ISSUE TITLE
翻译错误： whitespace => 空格

### ISSUE THREAD

**Issue by YanHuaSuiMei** [python/python-docs-zh-cn#176]
1. 英文网址: https://docs.python.org/3.8/library/stdtypes.html#str.strip
=>
中文网址: https://docs.python.org/zh-cn/3.8/library/stdtypes.html#str.strip

2. 原英文: If omitted or None, the chars argument defaults to removing whitespace.
=>
中文翻译: 如果省略或为 None，则 chars 参数默认移除空格符。

3. 错误之处: 该句将`whitespace`翻译为`空格`, 其实是`空白符`(正则中的`\s`, `[ \t\n\r\f]`).

4. 一个例子:
    ```
    >>> ' \t\n\r\f\van example with whitespace \t\n\r\f\v'.strip()
    'an example with whitespace'
    >>>
    ```

**Comment by silkriver** [comment]
fixed
