### ISSUE TITLE
中文文档4.6节翻译错误

### ISSUE THREAD

**Issue by Ranlajetech** [python/python-docs-zh-cn#179]
错误位置： [4.6. 定义函数](https://docs.python.org/zh-cn/3.9/tutorial/controlflow.html#defining-functions) 该小节末尾处。
错误描述： 原翻译“……不同类型定义不同的方法，不同类型的方法名可以相同，且**不会不会**引起歧义。”中，多了一个“不会”。
英文链接： [4.6. Defining Functions](https://docs.python.org/3.9/tutorial/controlflow.html#pass-statements)

**Comment by silkriver** [comment]
fixed
