### ISSUE TITLE
中文pdf文档不显示中文

### ISSUE THREAD

**Issue by lv896391** [python/python-docs-zh-cn#18]
是我的问题吗

**Comment by lv896391** [comment]
![image](https://user-images.githubusercontent.com/13609884/55273696-97512780-5309-11e9-9cfb-ba854d1985d1.png)

**Comment by zhsj** [comment]
已知问题，前天已经发 PR 修正，但还没生效。

https://github.com/python/docsbuild-scripts/pull/70

**Comment by silkriver** [comment]
可以下载epub文档看，我觉得比PDF好，有浏览器插件EPUBReader

**Comment by lv896391** [comment]
> 可以下载EPUB文档看，我觉得比PDF好，有浏览器插件EPUBReader

就是没找到好用的阅读器，试下这个

**Comment by zhsj** [comment]
官网上的pdf已经修正。
