### ISSUE TITLE
中文文档5.1.3节翻译错误

### ISSUE THREAD

**Issue by Ranlajetech** [python/python-docs-zh-cn#182]
- 错误位置：[5.1.3. 列表推导式](https://docs.python.org/zh-cn/3.9/tutorial/datastructures.html#list-comprehensions) “注意，循环结束后，创建（或重写）的名为 x 的变量仍然存在。这样就能计算平方列表的值，而且还没有任何副作用：……”
- 英文文档：[5.1.3. List Comprehensions](https://docs.python.org/3.9/tutorial/datastructures.html#list-comprehensions) "Note that this creates (or overwrites) a variable named x that still exists after the loop completes. We can calculate the list of squares without any side effects using: ..."
- 错误描述：原文中前后两句不是因果关系，而是描述了两种不同的方法，翻译与原意出入较大。
- 改进建议：“注意，这将创建（或覆盖）一个名为x的变量，该变量在循环结束后仍然存在。下述方法可以无副作用地计算平方列表：……”

**Comment by silkriver** [comment]
fixed
