### ISSUE TITLE
中文中夹杂的英文单词两侧未添加空格

### ISSUE THREAD

**Issue by atlanmatrix** [python/python-docs-zh-cn#185]
【目标链接】：https://docs.python.org/zh-cn/3/library/multiprocessing.html#pipes-and-queues
【问题位置】：管道和队列一节第二个注解中

原文：
当一个对象被放入一个队列中时，这个对象首先会被一个后台线程用pickle序列化

建议此处单词两侧添加空格，修改为：
当一个对象被放入一个队列中时，这个对象首先会被一个后台线程用 pickle 序列化

**Comment by silkriver** [comment]
fixed
