### ISSUE TITLE
页面展示了错误的标记字符

### ISSUE THREAD

**Issue by atlanmatrix** [python/python-docs-zh-cn#186]
【目标链接】：https://docs.python.org/3/library/multiprocessing.html#pipes-and-queues
【问题位置】：pipes-and-queues 一节

原文：
If you use JoinableQueue then you **must** call JoinableQueue.task_done() for each task removed from the queue or else the semaphore used to count the number of unfinished tasks may eventually overflow, raising an exception.

出现错误标记的地方：
如果你使用了 JoinableQueue ，那么你 \*\*必须\*\* 对每个已经移出队列的任务调用 JoinableQueue.task_done() 。不然的话用于统计未完成任务的信号量最终会溢出并抛出异常。

建议修改为：
如果你使用了 JoinableQueue ，那么你 **必须** 对每个已经移出队列的任务调用 JoinableQueue.task_done() 。不然的话用于统计未完成任务的信号量最终会溢出并抛出异常。

**Comment by silkriver** [comment]
fixed
