### ISSUE TITLE
未翻译的段落

### ISSUE THREAD

**Issue by atlanmatrix** [python/python-docs-zh-cn#187]
【目标链接】：https://docs.python.org/zh-cn/3/library/multiprocessing.html#pipes-and-queues
【问题位置】：pipes-and-queues 一节

该段落未翻译：
The Queue, SimpleQueue and JoinableQueue types are multi-producer, multi-consumer FIFO queues modelled on the queue.Queue class in the standard library. They differ in that Queue lacks the task_done() and join() methods introduced into Python 2.5's queue.Queue class.

**Comment by silkriver** [comment]
fixed
