### ISSUE TITLE
译文句意存在歧义

### ISSUE THREAD

**Issue by wind-chh** [python/python-docs-zh-cn#195]
【目标链接】：https://docs.python.org/zh-cn/3/library/functions.html#ascii
【问题位置】：ascii函数
原文：
As repr(), return a string containing a printable representation of an object, but escape the non-ASCII characters in the string returned by repr() using \x, \u or \U escapes. 

错误的译文翻译为：
与 repr() 类似，返回包含一个对象的可打印表示形式的字符串，但是 repr() 返回的字符串中非 ASCII 编码的字符会使用 \x、\u 和 \U 来转义。

建议翻译为：
与 repr() 类似，返回一个包含对象可打印表示形式的字符串，但是使用 \x、\u 和 \U 对 repr() 返回的字符串中非 ASCII 字符进行转义。

**Comment by songww** [comment]
fixed
