### ISSUE TITLE
library/subprocess#exceptions 的 `check_call` 错误地翻译成了 `check_all`

### ISSUE THREAD

**Issue by billchenchina** [python/python-docs-zh-cn#199]
原文: https://docs.python.org/3/library/subprocess.html#exceptions

译文: https://docs.python.org/zh-cn/3/library/subprocess.html#exceptions

[![check_call](https://user-images.githubusercontent.com/7758042/120896982-96894e00-c656-11eb-855b-d94493707686.png)](https://docs.python.org/3/library/subprocess.html#exceptions)

[![check_all](https://user-images.githubusercontent.com/7758042/120896988-a0ab4c80-c656-11eb-9934-a1ac0697ae7d.png)](https://docs.python.org/zh-cn/3/library/subprocess.html#exceptions)

**Comment by silkriver** [comment]
fixed
