### ISSUE TITLE
翻译勘误 语言参考-5.3.1-模块缓存

### ISSUE THREAD

**Issue by waynerv** [python/python-docs-zh-cn#20]
地址：https://docs.python.org/zh-cn/3.7/reference/import.html#the-module-cache

5.3.1. 模块缓存 第三段最后一句：
>  键也可以被同仁为 None，这将导致下次导入该模块时引发 ModuleNotFoundError。

英语原文为：
> The key can also be assigned to None, forcing the next import of the module to result in a ModuleNotFoundError.

这里的**同仁**应该为笔误，文档原意应为**赋值**。

**Comment by Dumeng** [comment]
@zhsj Fixed
