### ISSUE TITLE
itertools.product 说明翻译错误

### ISSUE THREAD

**Issue by cainmagi** [python/python-docs-zh-cn#201]
https://docs.python.org/zh-cn/3/library/itertools.html#itertools.product

在该函数的注释结尾，该段文字的翻译应当改为：

```diff
- 在 product() 运行之前，它会完全耗尽输入的可迭代对象，在内存中保留值的临时池以生成结果积。 相应地，它只适用于无限的输入。
+ 在 product() 运行之前，它会完全耗尽输入的可迭代对象，在内存中保留值的临时池以生成结果积。 相应地，它只适用于有限的输入。
```

### 参照原文：

Before product() runs, it completely consumes the input iterables, keeping pools of values in memory to generate the products. Accordingly, it is only useful with finite inputs.

**Comment by silkriver** [comment]
fixed
