### ISSUE TITLE
threading.Thread.setDaemon翻译错误

### ISSUE THREAD

**Issue by bestcondition** [python/python-docs-zh-cn#203]
英文[原文](https://docs.python.org/3/library/threading.html?highlight=thread#threading.Thread.setDaemon)写着
>Old getter/setter API for daemon; use it directly as a property instead.

中文简体[翻译](https://docs.python.org/zh-cn/3/library/threading.html?highlight=thread#threading.Thread.setDaemon)是这样
>旧的 name 取值/设值 API；建议直接当做特征属性使用它。

通篇看下来，在描述[name](https://docs.python.org/zh-cn/3/library/threading.html?highlight=thread#threading.Thread.setName)属性时是这样的
>旧的 name 取值/设值 API；直接当做特征属性使用它。

不难发现应该是翻译当时弄混了。

**Comment by silkriver** [comment]
fixed
