### ISSUE TITLE
漏字：《发起调用描述器》

### ISSUE THREAD

**Issue by c1ino** [python/python-docs-zh-cn#204]
1. 链接：https://docs.python.org/zh-cn/3/reference/datamodel.html#invoking-descriptors
2. 位置：《3.3.2.3. 发起调用描述器》一节中，倒数第二段。
3. 译文原文：
    >Python 方法 (包括 staticmethod() 和 classmethod()) 都是作为`非描述器`来实现的。因此实例可以重定义并重载方法。这允许单个实例获得与相同类的其他实例不一样的行为。
    
    >Python methods (including staticmethod() and classmethod()) are implemented as `non-data descriptors`. Accordingly, instances can redefine and override methods. This allows individual instances to acquire behaviors that differ from other instances of the same class.
    
    >https://docs.python.org/3/reference/datamodel.html#invoking-descriptors

4. 描述：`非描述器`也许应该是`非数据描述器`？

**Comment by silkriver** [comment]
fixed
