### ISSUE TITLE
class concurrent.futures.ThreadPoolExecutor有错别字

### ISSUE THREAD

**Issue by 0Jvang** [python/python-docs-zh-cn#208]
原文：在 3.5 版更改: 如果 max_workers 为 None 或没有指定，将默认为机器处理器的个数，假如 ThreadPoolExecutor 则重于 I/O 操作而不是 CPU 运算，那么可以乘以 5，同时工作线程的数量可以比 ProcessPoolExecutor 的数量高。

错误：则重于应改为侧重于

**Comment by silkriver** [comment]
fixed
