### ISSUE TITLE
Python3 中文文档错别字：datetime 标准库

### ISSUE THREAD

**Issue by NKID00** [python/python-docs-zh-cn#209]
链接：https://docs.python.org/zh-cn/3/library/datetime.html#datetime.date.fromordinal

位置：date.fromordinal 方法的第一句话

现译文：…其中公元 1 年 1 月 1 *晶*的序号为 1。

建议译文：…其中公元 1 年 1 月 1 **日**的序号为 1。

**Comment by silkriver** [comment]
fixed
