### ISSUE TITLE
形如 `__ init__` 的冗余空格

### ISSUE THREAD

**Issue by CCXXXI** [python/python-docs-zh-cn#210]
在 [dataclasses --- 数据类 — Python 3.9.6 文档](https://docs.python.org/zh-cn/3/library/dataclasses.html) 中发现了一些类似如下的内容：

> 将生成一个 __ init__() 方法

> 并必须使用 object.__ setattr__()

看起来有有冗余的空格，并且没有像[英文文档](https://docs.python.org/3/library/dataclasses.html)那样加上链接。

另外看网页源码是这个样子：

```html
将生成一个 <code class="xref py py-meth docutils literal notranslate"><span class="pre">__</span> <span class="pre">init__()</span></code> 方法
```

不确定其他页面是否有类似问题。

**Comment by silkriver** [comment]
fixed
