### ISSUE TITLE
疑似译文不准确两处《site —— 指定域的配置钩子》

### ISSUE THREAD

**Issue by c1ino** [python/python-docs-zh-cn#211]
- 页面链接：https://docs.python.org/zh-cn/3/library/site.html

------
1. 【第一处】（译文不准确）
 
译文：
>导入此模块将会附加域特定的路径到模块搜索路径并且添加一些内建对象，**除非**使用了 -S 选项`。在此例中`，模块可以被安全地导入，而不会对模块搜索路径和内建对象有自动的修改或添加。要明确地触发通常域特定的添加，调用函数 site.main()。
>
>在 3.3 版更改: `即便`使用了 -S，`也会`导入此模块`用于`触发路径操纵。

原文：
>Importing this module will append site-specific paths to the module search path and add a few builtins, **unless** -S was used. `In that case`, this module can be safely imported with no automatic modifications to the module search path or additions to the builtins. To explicitly trigger the usual site-specific additions, call the site.main() function.
>
>Changed in version 3.3: Importing the module `used to` trigger paths manipulation `even` when using -S.

改进：
>导入此模块将会附加域特定的路径到模块搜索路径并且添加一些内建对象，**除非**使用了 -S 选项`，那样的话`，模块可以被安全地导入，而不会对模块搜索路径和内建对象有自动的修改或添加。要明确地触发通常域特定的添加，调用函数 site.main()。
>
>在 3.3 版更改: `在之前即便`使用了 -S，导入此模块`仍然会`触发路径操纵。

------

2. 【第二处】（用词不一致）

译文：
>site —— `指定域`的配置钩子
>……
>要明确地触发通常`域特定`的添加
>……
> 在这些路径操作之后，会尝试导入一个名为 sitecustomize 的模块，它可以执行任意`站点专属`的定制。
> ……
> 在此之后，会尝试导入一个名为 usercustomize 的模块，它可以执行任意`用户专属`的定制
> ……

原文：
> site — `Site-specific` configuration hook
>……
>To explicitly trigger the usual `site-specific` additions
> ……
> After these path manipulations, an attempt is made to import a module named sitecustomize, which can perform arbitrary `site-specific` customizations.
> ……
> After this, an attempt is made to import a module named usercustomize, which can perform arbitrary `user-specific` customizations
> ……

改进：想不出更好的表达。
`site-specific`：`域特定`？`特定域`？`指定域`？`站点专属`？`域专属`？
`user-specific`：（同理）

------
- 描述：以上是大致思路，不一定对和准确，也不够通顺，也许有更好的翻译表达。

**Comment by silkriver** [comment]
fixed

**Comment by c1ino** [comment]
@silkriver 请问第一处中的第一个错处 `。在此例中` 是否被遗漏了？原文对应的`In that case`应该指的是“**除非使用了-S选项**”的情况。不催，只是问问。

**Comment by silkriver** [comment]
是的，谢谢提醒
