### ISSUE TITLE
疑似译文不准确《ChainMap 对象》

### ISSUE THREAD

**Issue by c1ino** [python/python-docs-zh-cn#212]
- 位置：https://docs.python.org/zh-cn/3/library/collections.html#collections.ChainMap.parents
- 译文、原文、提议：
>注意，一个 ChainMap() 的迭代顺序是通过**扫描`最后的`映射**来确定的:

>Note, the iteration order of a ChainMap() is determined by **scanning the mappings `last to first`**:

`通过扫描最后的映射来确定的` 也许应该是 `通过从最后一个映射开始往前扫描映射来确定` 之类的意思？

**Comment by silkriver** [comment]
fixed

**Comment by c1ino** [comment]
@silkriver 更正之后似乎还有点不清晰的地方？比如`该映射`应该指的是`参数中的多个映射`之类的？
>注意，一个 ChainMap() 的迭代顺序是通过从后往前扫描`该映射`来确定的:

>Note, the iteration order of a ChainMap() is determined by scanning the `mappings` last to first:

**Comment by silkriver** [comment]
改成了 所有映射
