### ISSUE TITLE
译文不准确两处《collections》《operator》

### ISSUE THREAD

**Issue by c1ino** [python/python-docs-zh-cn#213]
## 1. 【第一处】错字《collections --- 容器数据类型》
- 位置：https://docs.python.org/zh-cn/3/library/collections.html
- 译文、原文、提议：

>UserString 封装了`列表`对象，简化了字符串子类化

>UserString wrapper around `string` objects for easier string subclassing

`列表` 应该改为 `字符串`。

## 2. 【第二处】译文不准确《operator --- 标准运算符替代函数》
- 位置：https://docs.python.org/zh-cn/3/library/operator.html#operator.delitem

- 译文：
> ……
> operator.__delitem__(a, b)
>     移除`索引号 b 上的值 a`。
> ……
> operator.__getitem__(a, b)
>     返回`索引号 b 上的值 a`。
> ……
> operator.__setitem__(a, b, c)
>     将`索引号 b 上的值 a 设为 c`。

- 原文：
> ……
> operator.__delitem__(a, b)¶
>     Remove `the value of a at index b`.
> ……
> operator.__getitem__(a, b)
>     Return `the value of a at index b`.
> ……
> operator.__setitem__(a, b, c)
>     Set `the value of a at index b to c`.

- 提议：`索引号 b 上的值 a` 也许应该改为 `在 a 中索引号 b 上的值` 或者 `a 在索引号 b 上的值` 之类的？

**Comment by silkriver** [comment]
fixed
