### ISSUE TITLE
math模块文档三处翻译问题

### ISSUE THREAD

**Issue by Ranlajetech** [python/python-docs-zh-cn#214]
- [math.remainder(x, y)](https://docs.python.org/zh-cn/3.9/library/math.html#math.remainder) 第一段“…，则最近的 * even* 整数用于 n 。” even未翻译。[英文文档链接](https://docs.python.org/3.9/library/math.html#math.remainder)
- [math.ulp(x)](https://docs.python.org/zh-cn/3.9/library/math.html#math.ulp) 第四点应为“如果 x 等于0”，译文中0丢失。 [英文文档链接](https://docs.python.org/3.9/library/math.html#math.ulp)
- [math.log1p(x)](https://docs.python.org/zh-cn/3.9/library/math.html#math.log1p) “(base e)”未翻译且位置错误。[英文文档链接](https://docs.python.org/3.9/library/math.html#math.log1p)

**Comment by silkriver** [comment]
fixed
