### ISSUE TITLE
样式错误《3.9. 查找模块》

### ISSUE THREAD

**Issue by c1ino** [python/python-docs-zh-cn#215]
- 位置：https://docs.python.org/zh-cn/3/using/windows.html#finding-modules
## 译文
>……
>  "application paths" 可以同时添加到注册表` HKEY_CURRENT_USER` 和 HKEY_LOCAL_MACHINE 分支下的`:samp:\SOFTWARE\Python\PythonCore\{version}\PythonPath` 中作为子键。
> ……
> 如果``home`` 是一个绝对路径，并且 PYTHONHOME 未设置，
> ……
> 如果您不能使用前面的建议（例如，您是一个允许人们直接运行`：file:python.exe`的分发版），请确保安装目录中存在landmark 文件（`:file:Lib\os.py`）。

## 原文
> ……
> Additional “application paths” can be added in the registry as subkeys of `\SOFTWARE\Python\PythonCore{version}\PythonPath` under both the `HKEY_CURRENT_USER` and HKEY_LOCAL_MACHINE hives.
> ……
> If `home `is an absolute path and PYTHONHOME is not set, this path is used instead of the path to the main executable when deducing the home location.
> ……
> If you cannot use the previous suggestions (for example, you are a distribution that allows people to run `python.exe` directly), ensure that the landmark file (`Lib\os.py`) exists in your install directory.

## 提议
样式错误总共三处。只指出错处，不提供建议。
  1. 第一处：`HKEY_CURRENT_USER` 和 `:samp:\SOFTWARE\Python\PythonCore\{version}\PythonPath`
  2. 第二处：`home`
  3. 第三处：`：file:python.exe` 和 `:file:Lib\os.py`

**Comment by silkriver** [comment]
fixed
