### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by CCXXXI** [python/python-docs-zh-cn#216]
https://docs.python.org/zh-cn/3/library/argparse.html#parents

> 你在传\`\`parents=\`\`给那些解析器时必须完全初始化它们。如果你在子解析器之后改变父解析器是，这些改变不会反映在子解析器上。

~~Transifex 发了申请但还没过所以还是发到这里。~~

**Comment by CCXXXI** [comment]
同页

> The prefix_chars= 参数默认使用 '-'.

**Comment by silkriver** [comment]
fixed
