### ISSUE TITLE
疑似译文不准确四处《分发 Python 模块》

### ISSUE THREAD

**Issue by c1ino** [python/python-docs-zh-cn#217]
- 链接：https://docs.python.org/zh-cn/3/distributing/index.html
# 1.【第一处】错字：程序
- 译文、原文、提议：
>setuptools （在很大`程序`上）是作为 distutils 的取代者，

> setuptools is a (`largely`) drop-in replacement for distutils first published in 2004.

`在很大程序上` 应该改为 `在很大程度上`？

# 2.【第二处】漏字：包标准
- 译文、原文、提议：
> 在更为多样的 Python 版本之上为最新的`包标准`提供持续支持。

> that offers consistent support for more recent `packaging standards` across a wide range of Python versions.

`包标准` 指的应该是 `打包标准` ？

# 3.【第三处】译文不准确：安装工具
- 译文、原文、提议：
> ……相同的分发工具也可用于在组织内分发软件。
> `安装工具`
> 标准库不包括支持现代……

> ……regardless of whether that software is published as open source software or not.
> `Installing the tools`
> The standard library does not include……

`安装工具` 也许应该指的是 `安装相关工具` 之类的意思？两者字面意思不同。

# 4.【第四处】用词不一致/译文不准确：Python包用户指南
- 译文、原文、提议：
> `Python打包用户指南`包含有关 currently recommended tools 的更多详细信息。
> 阅读`Python包用户指南`
> “`Python包装用户指南`”介绍了创建和……

> `The Python Packaging User Guide` includes more details on the currently recommended tools.
> Reading `the Python Packaging User Guide`
> `The Python Packaging User Guide` covers the various key steps……

`Python包用户指南` 和 `Python包装用户指南` 也许应该都统一为 `Python打包用户指南`？

**Comment by silkriver** [comment]
fixed

**Comment by c1ino** [comment]
@silkriver 抱歉，原来漏看了两处：

> （例如用于协调`Python包装标准`开发的邮件列表的名称）。
>(such as the name of the mailing list used to coordinate `Python packaging standards` development).

> 参见 `Python 封装使用指南`：二进制扩展
> See also `Python Packaging User Guide`: Binary Extensions 

1. `Python包装标准` 应该是指 `Python打包标准`？
2. `Python 封装使用指南` 应该也是指 `Python打包用户指南` ？

**Comment by silkriver** [comment]
fixed
