### ISSUE TITLE
《内置函数/format》语句不通顺

### ISSUE THREAD

**Issue by Ranlajetech** [python/python-docs-zh-cn#218]
[简体中文](https://docs.python.org/zh-cn/3.9/library/functions.html#format)
[English](https://docs.python.org/3.9/library/functions.html#format)

- 第二段建议改为“…，它通常给出与调用 str(value) 相同的结果。”
- 第三段“…如果搜索到 object 有这个方法但 format_spec 不为空”部分，对应的英文为"… if the method search reaches object and the format_spec is non-empty"，这里"object"是指 object 类而不是变量名或实例，文档中这个 object 也是一个指向内置函数object() 的链接；”reach“指方法搜索退回到object基类，没有被翻译。建议改成：“…如果方法搜索退回到 object 类但 format_spec 不为空”

**Comment by silkriver** [comment]
fixed
