### ISSUE TITLE
《语言参考/概述》翻译有误

### ISSUE THREAD

**Issue by Ranlajetech** [python/python-docs-zh-cn#219]
[中文链接](https://docs.python.org/zh-cn/3.9/reference/introduction.html#notation)
[English](https://docs.python.org/3.9/reference/introduction.html#notation)

错误均在第三段。
1.
错误位置：第二句“竖线 (|) 被用来分隔可选项；它是此标注中最灵活的操作符。”
英文对应位置为：A vertical bar (|) is used to separate alternatives; it is the least binding operator in this notation.
建议译为：“竖线 (|) 被用来分隔可选项，它是此标注中绑定程度最低的操作符。”
（另：由于中英文语法和标点使用差异，英文句中的分号在译文中应修改为逗号）

2.
错误位置：”固定字符串包含在引号内。“
英文对应位置为：”Literal strings are enclosed in quotes.“
建议译为：”字符串字面值被包含在引号内。“

**Comment by silkriver** [comment]
fixed
