### ISSUE TITLE
管理员写个wiki 或者公告吧

### ISSUE THREAD

**Issue by ppcfish** [python/python-docs-zh-cn#22]
请把transifex到 github 到 travis-ci到docs.python.org的处理流程写个wiki，有变更公告一下吧
常见问题和要求也汇总说一下吧，不说提高效率了，至少避免新人猜坑吧

5号突然加了分支，编辑的内容提交到新分支了（这个自动提交的机制是什么？）
自己没有注意到，结果 反复在transifex 和github 3.7分支 和docs.python.org 核对，一个条目改了十几遍，都快不相信自己的眼睛了

浪费了大半天的时间，黑灯瞎火的全靠摸索...
感觉心好累，要修整一段时间...

**Comment by silkriver** [comment]
我猜是要等提交变绿勾才会更新到文档r吧 @zhsj

**Comment by zhsj** [comment]
Wiki 可以有，我先写了一个更新流程，https://github.com/python/python-docs-zh-cn/wiki/UpdateProcedure

后面把其他内容也更新上去吧，比如常见错误之类的。

**Comment by zhsj** [comment]
你写的wiki页面我删除了。。。把内容修订之后放在了 https://github.com/python/python-docs-zh-cn/wiki/CommonProblems#%E4%BF%AE%E6%AD%A3%E7%BC%96%E8%AF%91%E9%94%99%E8%AF%AF
