### ISSUE TITLE
Python3 中文文档错别字：cmd 标准库

### ISSUE THREAD

**Issue by NKID00** [python/python-docs-zh-cn#220]
链接：https://docs.python.org/zh-cn/3/library/cmd.html#cmd.Cmd.postloop

位置：Cmd.postloop() 方法的最后一句话

现译文：…*塔顶*存在是为了被子类覆盖。

建议译文：…**它的**存在是为了被子类覆盖。

**Comment by silkriver** [comment]
fixed
