### ISSUE TITLE
`re.findall` 未显示翻译

### ISSUE THREAD

**Issue by CCXXXI** [python/python-docs-zh-cn#223]
https://docs.python.org/zh-cn/3/library/re.html#re.findall

3.8 时有，之后就没了，看 transifex 上是存在的。

**Comment by silkriver** [comment]
未翻译的两段和 libary--re 中的文本有差异，看来并不在这个文件而是在还没翻到的某个文件中

**Comment by CCXXXI** [comment]
https://docs.python.org/zh-cn/3.9/library/json.html

有同样问题，看起来和 #232 有关

**Comment by CCXXXI** [comment]
上述两处已修正
