### ISSUE TITLE
同步出错了

### ISSUE THREAD

**Issue by silkriver** [python/python-docs-zh-cn#227]
好像不是因为文本格式问题

**Comment by Dumeng** [comment]
可以单独把37的Ubuntu版本制定为 `ubuntu-18.04`
https://github.com/python/python-docs-zh-cn/blob/2fd4a276ee5b5e0168fd7de58faf347df658566f/.github/workflows/python-37.yml#L12

**Comment by zhsj** [comment]
应该是 docutils 发布了 0.18 版本，和 sphinx 2.3.1 不兼容。sphinx 2.3.1 是在 https://github.com/python/cpython/blob/3.7/Doc/Makefile#L130 这里指定的。
