### ISSUE TITLE
译文错字三处《types》《zipfile》《io》

### ISSUE THREAD

**Issue by c1ino** [python/python-docs-zh-cn#228]
# 1. 萨芬内容《types》
[https://docs.python.org/zh-cn/3/library/types.html#types.ModuleType.__name__](https://docs.python.org/zh-cn/3/library/types.html#types.ModuleType.__name__)
> `萨芬内容`名称。

> The name of the `module`.

【提议】：`萨芬内容`改为`模块`。
> `模块`的名称。

# 2. 传入一个字典《zipfile》
https://docs.python.org/zh-cn/3/library/zipfile.html#command-line-interface
> 传入一个`字典`也是可接受的:

> Passing a `directory` is also acceptable:

【提议】：`字典`改为`目录`。
> 传入一个`目录`也是可接受的：

# 3. 定稿器《io》
https://docs.python.org/zh-cn/3/library/io.html#io.BufferedRandom
> 该构造器会为在第一个参数中给定的可查找原始流创建一个读取器和`定稿器`。 

> The constructor creates a reader and `writer` for a seekable raw stream, given in the first argument.

【提议】：`定稿器`改为`写入器`。
> 该构造器会为在第一个参数中给定的可查找原始流创建一个读取器和`写入器`。

**Comment by silkriver** [comment]
fixed
