### ISSUE TITLE
Po文件已更新，通过编译，但官方文档未更新

### ISSUE THREAD

**Issue by ppcfish** [python/python-docs-zh-cn#23]
Use/Windows.po 开始的第一小节，4个安装包的介绍（rst行号32-45），4个都翻出中文了，po文件有更新了
但是doc.python.org中，只有第3条有中文，其他还是英文
我等两天了，看两个分支都编译过了，为什么没更新到官方文档？还是我哪里写错了？

**Comment by zhsj** [comment]
我在wiki中写了更新的时间，这不是 *实时* 的。如果希望看到最新的效果，自己本地编译是最好的方法。

**Comment by silkriver** [comment]
我看到现在应该已更新了

**Comment by ppcfish** [comment]
我知道这个不是实时的。但是这段是在2天前译的，甚至之后译的内容都更新到官方文档了，这一段也是部分显示正常（3条英文1条中文）。我大概的翻了几遍官方文档，其他人译的也偶尔也有这样的情况。
所以才怀疑不是同步的问题，如果是我哪里写错了，请务必告知，以免下次继续踩坑 @silkriver 万分感谢
