### ISSUE TITLE
疑似译文不通顺三处《asyncio-future》《threading》《sched》

### ISSUE THREAD

**Issue by c1ino** [python/python-docs-zh-cn#230]
- [x] 1. 《asyncio-future》 `asyncio.Future.add_done_callback`
- [x] 2. 《threading》 `threading.Condition.notify`
- [x] 3. 《sched》 `sched.scheduler.run`

# 1. 《asyncio-future》`asyncio.Future.add_done_callback`
https://docs.python.org/zh-cn/3/library/asyncio-future.html#asyncio.Future.add_done_callback
> `If` the Future is already done when this method is called, the callback `is scheduled` with loop.call_soon().

> 调用这个方法时 Future 已经 完成 , 回调函数`已被` loop.call_soon() 调度。

【提议】：大概是下面这个意思？
> `如果`调用这个方法时 Future 已经完成，回调函数`会被` loop.call_soon() 调度。
    

# 2. 《threading》`threading.Condition.notify`
https://docs.python.org/zh-cn/3/library/threading.html#threading.Condition.notify
> Note: an awakened thread does not `actually return from` its wait() call until it can reacquire the lock. Since notify() does not release the lock, `its caller should`.

> 注意：被唤醒的线程`实际上不会返回`它调用的 wait() ，直到它可以重新获得锁。因为 notify() 不会释放锁，`只有它的调用者应该这样做`。

【提议】：翻译不够清晰？`return` 可能是 `恢复运行` 的意思而不是 `返回`？`its caller should` 可能指的是 `notify()的调用者` 而不是 `被唤醒的线程`？大意如下？
> 注意：被唤醒的线程`并没有真的恢复到`它调用的 wait() ，直到它可以重新获得锁。因为 notify() `不`释放锁，`其调用者才应该这样做`。

# 3. 《sched》`sched.scheduler.run`
https://docs.python.org/zh-cn/3/library/sched.html#sched.scheduler.run
> If a sequence of events takes longer to run than `the time available before the next event`, the scheduler will simply fall behind. No events will be `dropped`; `the calling code` is responsible for canceling events which are no longer pertinent.

> 如果一系列事件的运行时间比`下一个事件之前的可用时间`长，那么调度程序将完全落后。 不会`发生`任何事件；`调用代码`负责取消不再相关的事件。

【提议】：翻译不够清晰？`下一个事件之前的可用时间` 不太通顺？`不会发生` 可能指的是 `不会丢弃`？`调用代码` 所指是否不够清晰？大意如下？
> 如果一系列事件的运行时间`大于`下一个事件`发生前`的可用时间，那么调度程序将完全落后。 `没有事件会被丢弃`；调用代码负责取消不再相关的事件。

**Comment by silkriver** [comment]
fixed
