### ISSUE TITLE
Python 3.10 有什么新变化 Typo

### ISSUE THREAD

**Issue by 117503445** [python/python-docs-zh-cn#231]
https://docs.python.org/zh-cn/3/whatsnew/3.10.html#:~:text=%E5%80%8D%20~%201.17%20%E5%80%8D%EF%BC%8C-,lzma%20%E8%A7%A3%E5%8E%8B%E5%BF%AB%E4%B9%90,-1.20%20%E5%80%8D%20~%201.32

lzma 解压快乐 -> lzma 解压快了

**Comment by silkriver** [comment]
fixed
