### ISSUE TITLE
文档到 transifex 失去同步

### ISSUE THREAD

**Issue by laazy** [python/python-docs-zh-cn#232]
具体可见这个库 `__main__`
`https://www.transifex.com/python-doc/python-newest/translate/#zh_CN/library--__main__/326933106`
和文档中的：
`https://docs.python.org/zh-cn/3/library/__main__.html` 
并不同步。

**Comment by zhsj** [comment]
https://github.com/python/python-docs-zh-cn/wiki/UpdateProcedure

**Comment by silkriver** [comment]
这个原因还是不清楚，__main__文档有几十个条目但transifex上只有四个，完全对不上。

**Comment by laazy** [comment]
我的意思是说，这两个里面的原文内容不一致。

transifex  中的原文仅有4段，且除第一段外，其他均与官方文档中无对应。

实际上，现在transifex 中该页面最新版本保留的是3.9.7的原文和翻译，3.10并未同步进去。

**Comment by zhsj** [comment]
上传原文到transifex是ja团队负责的，看上去已经有几个月没有更新了

https://github.com/python-doc-ja/cpython-doc-catalog/tree/catalog-3.10/Doc/locales/pot

**Comment by laazy** [comment]
可否联系一下他们，或者由中文团队上传一份。

**Comment by inkydragon** [comment]
看起来他们用的 TravisCI 做的自动化。但是

> Since June 15th, 2021, the building on travis-ci.org is ceased. Please use travis-ci.com from now on.
> —— https://travis-ci.org/

所以有必要迁移到 github CI 了。

----

四处看了一下（[es](https://github.com/python/python-docs-es/blob/3.10/.github/workflows/main.yml)；[zh-tw](https://github.com/python/python-docs-zh-tw/blob/3.10/.github/workflows/ci.yml)；[fr](https://github.com/python/python-docs-fr/blob/3.10/.github/workflows/tests.yml)），貌似只有简体中文文档是依赖于 ja 团队的，其他语言的文档都是自托管的。
我们是否有必要自建 CI 管线？

**Comment by Dumeng** [comment]
tx的上传还是失去同步的状态

**Comment by fdx666666** [comment]
您好，邮件已收到，我会尽快查看。

**Comment by zhsj** [comment]
https://mail.python.org/pipermail/doc-sig/2021-November/thread.html

**Comment by laazy** [comment]
> https://mail.python.org/pipermail/doc-sig/2021-November/thread.html

所以源头的原因是官方的英文文档没有update到transifex吗？

**Comment by silkriver** [comment]
今天发现这个问题被解决了
