### ISSUE TITLE
tutorial appetite 缺少一段翻译

### ISSUE THREAD

**Issue by jaystone776** [python/python-docs-zh-cn#239]
https://docs.python.org/zh-cn/3/tutorial/appetite.html
第四段还是英文
You could write a Unix shell script or Windows batch files for some of these tasks, but shell scripts are best at moving around files and changing text data, not well-suited for GUI applications or games. You could write a C/C++/Java program, but it can take a lot of development time to get even a first-draft program. Python is simpler to use, available on Windows, macOS, and Unix operating systems, and will help you get the job done more quickly.

在这里没有找到对应的翻译内容，在翻译的界面里也没有列出，但这段在 3.8 里是有的
https://www.transifex.com/python-doc/python-newest/translate/#zh_CN/tutorial--appetite/326965076

**Comment by fdx666666** [comment]
您好，邮件已收到，我会尽快查看。

**Comment by silkriver** [comment]
应该还是 #232 的问题
