### ISSUE TITLE
Issue from mailing list

### ISSUE THREAD

**Issue by encukou** [python/python-docs-zh-cn#240]
Hello,
The following report was [sent to the docs mailing list](https://mail.python.org/archives/list/docs@python.org/thread/PARLBDHLLVTLXZ3Z657TBZ4MUGBBTK4G/). I don't understand Chinese, but I'm reposting on behalf of @LXYan2333.

---

The Simplified Chinese translation has some faults.

https://docs.python.org/zh-cn/3/tutorial/classes.html#python-scopes-and-namespaces

here,  (Actually, forgetting would be a better way to describe what actually happens.) is wrongly translated to（事实上，比起描述到底发生了什么，忘掉它更好。）

 

the English doc:

 
![image](https://user-images.githubusercontent.com/302922/154966828-0aba84c0-845f-455f-bdf1-9fe7a5e8d418.png)

The wrongly translated Simplified Chinese doc:
![image](https://user-images.githubusercontent.com/302922/154966853-4e956f89-f859-4924-8568-065bbdf6dbd6.png)

 

 

Right translation should be like “实际上，用“遗忘”来描述实际发生的情况会更好。

**Comment by silkriver** [comment]
fixed
