### ISSUE TITLE
Wrong translation in `fnmatch` module

### ISSUE THREAD

**Issue by ayaka14732** [python/python-docs-zh-cn#241]
Note that the filename separator ('/' on Unix) is not special to this module. See module [glob](https://docs.python.org/3/library/glob.html#module-glob) for pathname expansion ([glob](https://docs.python.org/3/library/glob.html#module-glob) uses [filter()](https://docs.python.org/3/library/fnmatch.html#fnmatch.filter) to match pathname segments). Similarly, filenames starting with a period are not special for this module, and are matched by the * and ? patterns.

注意文件名分隔符 (Unix 上为 '/') 不是 此模块所特有的。 请参见 [glob](https://docs.python.org/zh-cn/3/library/glob.html#module-glob) 模块了解文件名扩展 ([glob](https://docs.python.org/zh-cn/3/library/glob.html#module-glob) 使用 [filter()](https://docs.python.org/zh-cn/3/library/fnmatch.html#fnmatch.filter) 来匹配文件名的各个部分)。 类似地，以一个句点打头的文件名也不是此模块所特有的，可以通过 * 和 ? 模式来匹配。

---

原文 special 不是「特有的」，而是「特别的」，意思是 `fnmatch` 模块不会对 `/` 和 `.*` 作单独处理，也就是说它们和普通文件名一样，没有什么特别的。

**Comment by silkriver** [comment]
fixed
