### ISSUE TITLE
同步失败了

### ISSUE THREAD

**Issue by silkriver** [python/python-docs-zh-cn#248]
之前3.7同步失败，现在全部失败了

**Comment by silkriver** [comment]
20220617文档经过清理解决了很多问题，但之后3.10同步就一直失败，有一个无提示位置的错误 @zhsj

**Comment by Dumeng** [comment]
找到了问题：
- `` `foo<http://foo.bar/>`__ `` -> ❌
- `` `foo http://foo.bar/>`__ ``: -> ❌
- `` `foo <http://foo.bar/>`__ ``: -> ✅

https://superuser.com/questions/1669143/cryptic-error-from-sphinx-anonymous-hyperlink-mismatch
