### ISSUE TITLE
内置常量翻译少一个字

### ISSUE THREAD

**Issue by simonclouds** [python/python-docs-zh-cn#25]
原文
```
A small number of constants live in the built-in namespace. 
```
译文：
```
量常量存在于内置命名空间中。
```
应该是少量常量存在于内置命名空间中。 

python 3.7.3 版本中译文版本。

**Comment by silkriver** [comment]
fixed

**Comment by cIark** [comment]
[9.2](https://docs.python.org/zh-cn/3.7/tutorial/classes.html#python-scopes-and-namespaces)
namespace 是一个从名字到对象的映射。大部分命名空间当前都由 Python 字典实现，但一般情况下基本不会去关注它们（除了要面对性能问题时），而且也有可能在将来更改。下面是几个命名空间的例子：存放内置函数的集合（包含 abs() 这样的函数，和内建的异常等）；模块中的全局名称；函数调用中的本地名称。从某种意义上说，**对象的的属性集合也是一种命名空间的形式**。关于命名空间的重要一点是，不同命名空间中的名称之间绝对没有关系；例如，两个不同的模块都可以定义函数“最大化”而不会产生混淆 - 模块的用户必须在其前面加上模块名称。
**对象的的属性集合，两个“的”~**

**Comment by silkriver** [comment]
fixed
