### ISSUE TITLE
“对象注解属性的最佳实践”翻译错误

### ISSUE THREAD

**Issue by st1020** [python/python-docs-zh-cn#250]
“在 Python 3.9 以上版本中访问对象的注解字典”的原文为“Accessing The Annotations Dict Of An Object In Python 3.9 And Older”，应翻译为“在 Python 3.9 及更早的版本中访问对象的注解字典”
https://docs.python.org/zh-cn/3/howto/annotations.html

**Comment by songww** [comment]
Fixed
