### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by imba-tjd** [python/python-docs-zh-cn#252]
https://docs.python.org/zh-cn/3/library/datetime.html#datetime.timedelta.total_seconds

> 返回时间间隔包含了多少秒。造价于 td / timedelta(seconds=1)。

`造价于` -> `等价于`

---

https://docs.python.org/zh-cn/3/library/datetime.html#datetime.datetime.fromtimestamp

> 返回的 datetime 对象将为天真型

`天真型` -> `简单型`

**Comment by songww** [comment]
感谢，已修复

**Comment by imba-tjd** [comment]
https://docs.python.org/zh-cn/3/howto/regex.html#common-problems 的上一段

> 使用模块级别 re.sub() 函数时，模式作为第一个参数传递。 图案可以作为对象或字符串提供

`图案` -> `模式`

**Comment by songww** [comment]
> https://docs.python.org/zh-cn/3/howto/regex.html#common-problems 的上一段
> 
> > 使用模块级别 re.sub() 函数时，模式作为第一个参数传递。 图案可以作为对象或字符串提供
> 
> `图案` -> `模式`

Fixed

**Comment by imba-tjd** [comment]
https://docs.python.org/zh-cn/3/library/multiprocessing.html#multiprocessing.pool.Pool.map

> 可以将 chunksize 设置为一个正整数从而（近似）指定每个块的大小可以。

结尾多了一个“可以”

> 可以考虑使用 imap() 或 imap_unordered() 并且显示指定 chunksize 以提升效率。

显示 -> 显式
