### ISSUE TITLE
Translation optimization

### ISSUE THREAD

**Issue by tuzi3040** [python/python-docs-zh-cn#253]
[3.10.4 Documentation » Python 标准库 » 内置函数 » open()](https://docs.python.org/zh-cn/3/library/functions.html#open)

> When open() is used to open a file in a text mode ('w', 'r', 'wt', 'rt', etc.), it returns a subclass of io.TextIOBase (specifically io.TextIOWrapper).

> 打开文件时，它将返回 io.TextIOBase (特别是 io.TextIOWrapper) 的一个子类。

This may be better:
`打开文件时，它将返回 io.TextIOBase 的一个子类 (具体为 io.TextIOWrapper)。`

`特别是` feels like `especially`.

**Comment by fdx666666** [comment]
您好，邮件已收到，我会尽快查看。

**Comment by songww** [comment]
Fixed
