### ISSUE TITLE
pathlib.Path.rglob的一处小问题

### ISSUE THREAD

**Issue by muziing** [python/python-docs-zh-cn#257]
<https://docs.python.org/zh-cn/3/library/pathlib.html#pathlib.Path.rglob>

目前显示的内容为

> 这就像调用 Path.glob\`时在给定的相对 \*pattern\* 前面添加了"\`\`\*\*/`()"

应为

> 这就像调用 [`Path.glob()`](https://docs.python.org/zh-cn/3/library/pathlib.html#pathlib.Path.glob) 时在给定的相对 *pattern* 前面添加了"`**/`"

**Comment by silkriver** [comment]
fixed
