### ISSUE TITLE
pickle文档一处微小问题

### ISSUE THREAD

**Issue by muziing** [python/python-docs-zh-cn#259]
<https://docs.python.org/zh-cn/3.10/library/pickle.html>（3.8 及以后版本的文档）开头的「警告」部分：

> pickle 模块\*\*并不安全\*\*。你只应该对你信任的数据进行unpickle操作。
>
> 构建恶意的 pickle 数据来\*\*在解封时执行任意代码\*\*是可能的。绝对不要对不信任来源的数据和可能被篡改过的数据进行解封。

加粗语法未能被正确识别，而双星号直接显示在文本中。应为：

> pickle 模块**并不安全**。你只应该对你信任的数据进行unpickle操作。
>
> 构建恶意的 pickle 数据来**在解封时执行任意代码**是可能的。绝对不要对不信任来源的数据和可能被篡改过的数据进行解封。

希望我“吹毛求疵”的 issue 能帮助中文文档翻译精益求精。

**Comment by silkriver** [comment]
fixed
