### ISSUE TITLE
[勘误] 正则表达式非捕获匹配组语法的描述歧义

### ISSUE THREAD

**Issue by DanielW10001** [python/python-docs-zh-cn#26]
位置: [文档 » Python 标准库 » 文本处理服务 » re --- 正则表达式操作 » 正则表达式语法 » (?:…)](https://docs.python.org/zh-cn/3/library/re.html#regular-expression-syntax)
[译文](https://docs.python.org/zh-cn/3/library/re.html#regular-expression-syntax):
> `(?:…)`
> 正则括号的非捕获版本。只识别，不取值。匹配在括号内的任何正则式，但匹配完成后，这个子串不做为结果被获取。比如 (?:a)bc 指定了匹配样式 bc，但这个样式前面必须是字符 a，它可以匹配 'abc'，但不能匹配 'bbc'，匹配完成后只返回 'bc' 作为匹配内容。

[原文](https://docs.python.org/3/library/re.html#regular-expression-syntax):
> `(?:...)`
> A non-capturing version of regular parentheses. Matches whatever regular expression is inside the parentheses, but the substring matched by the group cannot be retrieved after performing a match or referenced later in the pattern.

`(?:...)`结构不会将匹配内容作为一个单独的捕获组内容, 但仍会讲匹配内容作为整体匹配的一部分. 示例如下:
```python
>>> import re
>>> re.match(r"abc", "abc")
<re.Match object; span=(0, 3), match='abc'>
>>> re.match(r"(?:a)bc", "abc")
<re.Match object; span=(0, 3), match='abc'>
```
注意到`(?:a)bc`捕获内容为`abc`而非`bc`.

**Comment by silkriver** [comment]
fixed
