### ISSUE TITLE
单词拼写错误

### ISSUE THREAD

**Issue by cxyxlxdm** [python/python-docs-zh-cn#261]
坐标：https://docs.python.org/zh-cn/3/library/venv.html#an-example-of-extending-envbuilder
setuptotols 应为 setuptools
<img width="821" alt="Snipaste_2022-06-28_10-41-20" src="https://user-images.githubusercontent.com/5643349/176080334-b02f7761-25f6-4680-9c67-20449f924e03.png">

**Comment by songww** [comment]
Fixed
