### ISSUE TITLE
multiprocessing中的一处翻译错误

### ISSUE THREAD

**Issue by passerbyzhao** [python/python-docs-zh-cn#264]
- 地址：[https://docs.python.org/zh-cn/3/library/multiprocessing.html#all-start-methods](https://docs.python.org/zh-cn/3/library/multiprocessing.html#all-start-methods)  
`避免杀死进程`子项第一句
- 原文：
> Using the [Process.terminate](https://docs.python.org/3/library/multiprocessing.html#multiprocessing.Process.terminate) method to stop a...
- 译文：
> 听过 [Process.terminate](https://docs.python.org/zh-cn/3/library/multiprocessing.html#multiprocessing.Process.terminate)  停止一个进程...
- 错误：`听过`应该为`通过`

**Comment by songww** [comment]
Fixed
