### ISSUE TITLE
threading-信号量对象一处格式错误

### ISSUE THREAD

**Issue by passerbyzhao** [python/python-docs-zh-cn#265]
- 地址：[https://docs.python.org/zh-cn/3/library/threading.html#semaphore-objects](https://docs.python.org/zh-cn/3/library/threading.html#semaphore-objects)
`class threading.Semaphore(value=1)`的`acquire(blocking=True, timeout=None)`子项中
- 原译文：`当 blocking 设置为 False``时调用，不会阻塞。如果没有参数的调用会阻塞，立即返回``False；`
> 当 blocking 设置为 False``时调用，不会阻塞。如果没有参数的调用会阻塞，立即返回``False；
- 应当为：``当 blocking 设置为 `False`时调用，不会阻塞。如果没有参数的调用会阻塞，立即返回`False`；``
> 当 blocking 设置为 `False`时调用，不会阻塞。如果没有参数的调用会阻塞，立即返回`False`；

**Comment by silkriver** [comment]
fixed
