### ISSUE TITLE
Python3.10 pathlib 中一些翻译问题

### ISSUE THREAD

**Issue by miaotony** [python/python-docs-zh-cn#266]
https://docs.python.org/zh-cn/3/library/pathlib.html 

## 1
> 参见 [PEP 428](https://www.python.org/dev/peps/pep-0428)：pathlib 模块 -- 面向对象的的文件系统路径。

两个 _的_ 重复了

## 2
[PurePath.parents](https://docs.python.org/zh-cn/3/library/pathlib.html#pathlib.PurePath.parents) 处漏翻译，且注解应该改一下

> 在 3.10 版更改: parents 序列现在支持 [切片](https://docs.python.org/zh-cn/3/glossary.html#term-slice) 负的索引值。

依据原文，应该改成 
parents 序列现在支持 [切片](https://docs.python.org/zh-cn/3/glossary.html#term-slice) **以及**负的索引值。

## 3
[PurePath.parent](https://docs.python.org/zh-cn/3/library/pathlib.html#pathlib.PurePath.parent) 
> 如果你想要向上移动任意文件系统路径

改成 ”如果你想要向上 **遍历** 任意文件系统路径“ 感觉更好

**Comment by songww** [comment]
Fixed

**Comment by miaotony** [comment]
> Fixed

[PurePath.parents](https://docs.python.org/zh-cn/3/library/pathlib.html#pathlib.PurePath.parents) 处漏翻译，还没修

![](https://user-images.githubusercontent.com/41962043/177755913-7aa4fe5d-96cb-49b3-bd88-583ef7d52417.png)

> An immutable sequence providing access to the logical ancestors of the path:

可以翻译成  
> 一个不可变序列，提供对此路径的逻辑祖先（所有逻辑父路径）的访问：
