### ISSUE TITLE
求：相同条目2次修改后无法自动同步的补救方法

### ISSUE THREAD

**Issue by ppcfish** [python/python-docs-zh-cn#27]
一个资源，如果在transifex的多个版本中同时存在

在第一次译的时候（由空白到第一次保存），保存内容会自动同步下去
python-newest  -->Python 3.6  -->Python 3.5  -->Python ...
上面除了第一个是自己保存的，后面的条目都是自动同步下去的（TRANSLATED BY TM）

如果非常不幸保存错了，再次修改保存的内容就无法同步下去了，得逐一手工修改
有没有好的补救方法？

**Comment by zhsj** [comment]
应该没有。。

但我们现在只翻译 python-newest 中的条目，不用关心 <3.7 中的内容。

官网上即使有  < 3.7 版本的中文文档，也是用 python-newest 里的内容来编译的。

**Comment by ppcfish** [comment]
哦，那我就放心了
