### ISSUE TITLE
dataclasses.make_dataclass用詞翻譯不當

### ISSUE THREAD

**Issue by WendaoLee** [python/python-docs-zh-cn#271]
[make_dataclass](https://docs.python.org/zh-cn/3.10/library/dataclasses.html#dataclasses.make_dataclass)介紹的第一句中，文檔内容為：
> 新建一个名为 cls_name 的数据库

而原文為：
> Creates a new dataclass with name cls_name

將*dataclass*翻譯為*數據庫*可能是譯者將自己的認識代入進來了，但是這樣可能會造成小白查閲文檔時的疑惑。建議此處不作翻譯。

另：簡繁中文檔都在此處將dataclass翻譯爲了數據庫。建議修改。

**Comment by songww** [comment]
简中已修复

另：繁中的bug反馈不在这里，这里的人大多也没繁中的权限

**Comment by WendaoLee** [comment]
> 简中已修复
> 
> 另：繁中的bug反馈不在这里，这里的人大多也没繁中的权限

瞭解，謝謝。
