### ISSUE TITLE
3.9及以上版本中错误一处

### ISSUE THREAD

**Issue by muziing** [python/python-docs-zh-cn#272]
<https://docs.python.org/zh-cn/3.9/library/stdtypes.html#str.removeprefix>

`str.removeprefix` 中的 *`prefix`* 为参数，在描述中应以英文原貌呈现。而目前的文档将其进行了翻译，显示为 *`前缀`*

`str.removesuffix` 中也有类似的问题。

**Comment by songww** [comment]
fixed
