### ISSUE TITLE
修正翻译错误

### ISSUE THREAD

**Issue by androllen** [python/python-docs-zh-cn#276]
[中文地址](https://docs.python.org/zh-cn/3/library/winreg.html)
建立到另一台**计算上**上的预定义注册表句柄的连接，并返回一个 handle 对象.
[英文地址](https://docs.python.org/3/library/winreg.html)
Establishes a connection to a predefined registry handle on **another computer**, and returns a handle object.

**计算上** 应改为  **计算机**

**Comment by silkriver** [comment]
fixed
