### ISSUE TITLE
concurrent.futures 中两处翻译错误

### ISSUE THREAD

**Issue by labo-China** [python/python-docs-zh-cn#277]
https://docs.python.org/zh-cn/3/library/concurrent.futures.html

在 ThreadPoolExecutor 下面第二行

原文：
>“当回调已关联了一个 Future 然后再等待另一个Future 的结果时就会发产死锁情况。例如:”

其中的 “再” 应改为 “在”，“发产” 应改为 “导致”

**Comment by silkriver** [comment]
fixed
