### ISSUE TITLE
多了一个s

### ISSUE THREAD

**Issue by green961** [python/python-docs-zh-cn#280]
[import_module](https://docs.python.org/zh-cn/3/library/importlib.html#importlib.import_module)
importlib.import_module(name, `package`=None)
导入一个模块。参数 name 指定了以绝对或相对导入方式导入什么模块 (比如要么像这样 pkg.mod 或者这样 ..mod)。如果参数 name 使用相对导入的方式来指定，那么那个参数 `packages` 必须设置为那个包名

多了一个s

**Comment by green961** [comment]
这意味着该函数的所有`主义`都来自于 [importlib.__import__()](https://docs.python.org/zh-cn/3/library/importlib.html#importlib.__import__)。

是 语义 吧

**Comment by green961** [comment]
如果动态导入一个自~从~解释器开始执行以来被创建的模块

可以把 从 去掉

**Comment by silkriver** [comment]
fixed
