### ISSUE TITLE
Inspect 标准库文档错字

### ISSUE THREAD

**Issue by kanglmf** [python/python-docs-zh-cn#281]
https://docs.python.org/zh-cn/3/library/inspect.html?highlight=inspect#inspect.CO_VARKEYWORDS

原文：
`代码对象拥有一个可变关键字形惨死（类似 **kwrags）。`

应为:
`代码对象拥有一个可变关键字形参（类似 **kwrags）。`

**Comment by silkriver** [comment]
fixed
