### ISSUE TITLE
翻译错误

### ISSUE THREAD

**Issue by Etuloser** [python/python-docs-zh-cn#287]
https://docs.python.org/zh-cn/3/library/threading.html#thread-objects
线程对象的start方法翻译是否有误
![Z IIF8HMO4$15KO_J DL%{Y](https://user-images.githubusercontent.com/19371594/196360983-84e74e80-12df-4d09-9779-3ef01ff983df.png)
![9% OMZE(P34D_)WAOU0)YV](https://user-images.githubusercontent.com/19371594/196361023-56ad0cee-2ab9-4208-9cb9-d7c15eed585e.png)
是否应该为控制线程

**Comment by silkriver** [comment]
fixed
