### ISSUE TITLE
Python 3.11 发布了

### ISSUE THREAD

**Issue by silkriver** [python/python-docs-zh-cn#289]
汉化文档需要相应的更新

https://github.com/python/python-docs-zh-cn/issues/289#tasklist-block-7754debf-7f8e-42ab-87c3-1434a56bf06a

**Comment by silkriver** [comment]
同步停了 @zhsj

**Comment by WendaoLee** [comment]
> 同步停了 @zhsj 

不懂就問，同步停了是在transifex上翻譯的都不會同步到官方文檔上嗎？👀

**Comment by zhsj** [comment]
> 不懂就問，同步停了是在transifex上翻譯的都不會同步到官方文檔上嗎？eyes

是。

我手工停掉的。等把CI更新到3.11之后再重新开启。

**Comment by WendaoLee** [comment]
> > 不懂就問，同步停了是在transifex上翻譯的都不會同步到官方文檔上嗎？eyes
> 
> 是。
> 
> 我手工停掉的。等把CI更新到3.11之后再重新开启。

了解了。谢谢。
