### ISSUE TITLE
错别字

### ISSUE THREAD

**Issue by JezaChen** [python/python-docs-zh-cn#290]
在[functools文档的@functools.singledispatch章节中](https://docs.python.org/zh-cn/3/library/functools.html#functools.singledispatch)，“要访问所有**忆**注册实现，请使用只读的 registry 属性”中的“**亿**”应该改为“**已**”。
![截图 2022-10-31 22-38-49](https://user-images.githubusercontent.com/31545780/199034692-afc6a8c8-f7e8-4ece-ac22-10dc52c957e3.png)

**Comment by silkriver** [comment]
fixed
