### ISSUE TITLE
标准库里关于subprocess.STDOUT翻译错误

### ISSUE THREAD

**Issue by shzhxh** [python/python-docs-zh-cn#291]
#### 原文链接对比
[中文版](https://docs.python.org/zh-cn/3/library/subprocess.html#subprocess.STDOUT)
[英文版](https://docs.python.org/3/library/subprocess.html#subprocess.STDOUT)
#### 修改建议
应把：**可被 [Popen](https://docs.python.org/zh-cn/3/library/subprocess.html#subprocess.Popen) 的 stdin ， stdout 或者 stderr 参数使用的特殊值**
改为：**可被 [Popen](https://docs.python.org/zh-cn/3/library/subprocess.html#subprocess.Popen) 的 stderr 参数使用的特殊值**

**Comment by WendaoLee** [comment]
Fixed.
感謝您的提醒。
