### ISSUE TITLE
错别字

### ISSUE THREAD

**Issue by dkymore** [python/python-docs-zh-cn#295]
https://docs.python.org/zh-cn/3/library/winreg.html#functions

> winreg.CreateKeyEx(key, sub_key, reserved=0, access=KEY_WRITE)
> reserved 是一个保留的证书，必须是零。默认值为零。

英文：`reserved is a reserved integer, and must be zero. The default is zero.` 

证书 应为 整数

**Comment by fdx666666** [comment]
您好，邮件已收到，我会尽快查看。
