### ISSUE TITLE
翻译不准确

### ISSUE THREAD

**Issue by green961** [python/python-docs-zh-cn#299]
https://docs.python.org/zh-cn/3/library/collections.html#collections.ChainMap.parents

注意，一个 [ChainMap()](https://docs.python.org/zh-cn/3/library/collections.html#collections.ChainMap) 的迭代顺序是通过从后往前扫描所有映射来确定的:

>>>
baseline = {'music': 'bach', 'art': 'rembrandt'}
adjustments = {'art': 'van gogh', 'opera': 'carmen'}
list(ChainMap(adjustments, baseline))
['music', 'art', 'opera']
~~这给出了与 [dict.update()](https://docs.python.org/zh-cn/3/library/stdtypes.html#dict.update) 调用序列相同的顺序，从最后一个映射开始:~~

英文：This gives the same ordering as a series of [dict.update()](https://docs.python.org/3/library/stdtypes.html#dict.update) calls starting with the last mapping:
谷歌翻译：[dict.update()](https://docs.python.org/3/library/stdtypes.html#dict.update)这给出了与从最后一个映射开始的一系列调用相同的顺序：
意译：下面的 [dict.update()](https://docs.python.org/zh-cn/3/library/stdtypes.html#dict.update) 给出了与上面从最后一个映射开始调用序列相同的顺序

**Comment by fdx666666** [comment]
您好，邮件已收到，我会尽快查看。

**Comment by silkriver** [comment]
fixed
