### ISSUE TITLE
2.7版本

### ISSUE THREAD

**Issue by WillSkywalker** [python/python-docs-zh-cn#30]
Python 2.7 版本连基础的 tutorial 部分都没有翻译完成，甚至在transifex已经翻译的部分都已经不会更新。虽然 Python 2 已经不再支持，但是毕竟legacy数量众多，基础部分还是应该考虑完成（可以大幅借鉴 Python 3 文档）

**Comment by Dumeng** [comment]
Python 2.7的生命周期将在今年底全面结束，该版本的官方文档可能将被归档，不再提供直接入口

**Comment by silkriver** [comment]
大部分条目确实都可以看到翻译建议，但内容都有细微差别，不能直接照搬。
