### ISSUE TITLE
翻译不当

### ISSUE THREAD

**Issue by Lastprismer** [python/python-docs-zh-cn#303]
https://docs.python.org/zh-cn/3/howto/regex.html#grouping

> 例如，以下正则检测字符串中的双字。:
&gt;&gt;&gt; p = re.compile(r'\b(\w+)\s+\1\b')
&gt;&gt;&gt; p.search('Paris in the the spring').group()
'the the'

英文：

> For example, the following RE detects doubled words in a string.

“双字”应为“两个连续的单词”或近义

**Comment by silkriver** [comment]
fixed
