### ISSUE TITLE
python310, 311 内置函数`ascii`翻译错误

### ISSUE THREAD

**Issue by YanHuaSuiMei** [python/python-docs-zh-cn#306]
[python3.10 内置函数 ascii 中文翻译](https://docs.python.org/zh-cn/3.10/library/functions.html#ascii)
---
与 [repr()](https://docs.python.org/zh-cn/3.10/library/functions.html#repr) 类似，返回一个字符串，表示对象的可打印形式，
_**但在 [repr()](https://docs.python.org/zh-cn/3.10/library/functions.html#repr) 返回的字符串中，非 ASCII 字符会用 \x、\u 和 \U 进行转义。**_
生成的字符串类似于 Python 2 中 [repr()](https://docs.python.org/zh-cn/3.10/library/functions.html#repr) 的返回结果。

[python3.10 内置函数 ascii 原文](https://docs.python.org/3.10/library/functions.html#ascii)
---
As [repr()](https://docs.python.org/3.10/library/functions.html#repr), return a string containing a printable representation of an object,
**_but escape the non-ASCII characters in the string returned by [repr()](https://docs.python.org/3.10/library/functions.html#repr) using \x, \u, or \U escapes._**
This generates a string similar to that returned by [repr()](https://docs.python.org/3.10/library/functions.html#repr) in Python 2.

问题
---
加粗斜体内容翻译错误.
python3.10, 3.11的翻译是错误的, python3.9的翻译是正确的.

[python3.9 内置函数 ascii 中文翻译](https://docs.python.org/zh-cn/3.9/library/functions.html#ascii)
---
与 [repr()](https://docs.python.org/zh-cn/3.9/library/functions.html#repr) 类似，返回一个包含对象的可打印表示形式的字符串，
**_但是使用 \x、\u 和 \U 对 [repr()](https://docs.python.org/zh-cn/3.9/library/functions.html#repr) 返回的字符串中非 ASCII 编码的字符进行转义。_** 
生成的字符串和 Python 2 的 [repr()](https://docs.python.org/zh-cn/3.9/library/functions.html#repr) 返回的结果相似。

**Comment by WendaoLee** [comment]
Fixed.
