### ISSUE TITLE
已移除 应 修改为 已弃用

### ISSUE THREAD

**Issue by tasty0tomato** [python/python-docs-zh-cn#307]
https://docs.python.org/zh-cn/3.10/library/typing.html?highlight=list
文中出现了很多“3.9 版后已移除”
但是英文原文为“Deprecated since version 3.9”而非“Removed since version 3.9”
所以“弃用”应该更符合原文意图

**Comment by WendaoLee** [comment]
并不影响理解。我个人觉得没必要更改。

若您想要修改，可前往[transifex](https://www.transifex.com/python-doc/python-310)进行相关修改。

**Comment by silkriver** [comment]
此文本实际上不在这个文件里，目前也没有办法试，因为翻译文本同步已经停很久了，要等 @zhsj 来处理

**Comment by BlueGlassBlock** [comment]
此文本应该是由 Sphinx 直接提供的，对应的 `po` 文件在此处：https://github.com/sphinx-doc/sphinx/blob/92c4874620d4ae4e785b00a4635f61f64da90f59/sphinx/locale/zh_CN/LC_MESSAGES/sphinx.po
