### ISSUE TITLE
分发 Python 模块（遗留版本） 是否有必要翻译？

### ISSUE THREAD

**Issue by ppcfish** [python/python-docs-zh-cn#31]
分发 Python 模块（遗留版本）https://docs.python.org/zh-cn/3/distutils/index.html

该小节在docs.python.org已经没有入口，且在总目录中 https://docs.python.org/zh-cn/3/contents.html 都不存在了

但该小节及下面的子小节，都继续在transifex仍挂着，该小节是否有必要翻译？

**Comment by Dumeng** [comment]
可以考虑先翻译其他优先级高的部分

**Comment by ppcfish** [comment]
还有这小节更厉害，在transifex挂着，但在docs.python.org都搜索不到了
https://www.transifex.com/python-doc/python-newest/translate/#zh_CN/install--index/108382135

是管理更新错资源文件了？

**Comment by Dumeng** [comment]
https://docs.python.org/zh-cn/3/install/index.html
同样已经移除入口

**Comment by ppcfish** [comment]
了解
