### ISSUE TITLE
错别字一处

### ISSUE THREAD

**Issue by JellyfisHawthorn** [python/python-docs-zh-cn#314]
地址：[https://docs.python.org/zh-cn/3.11/library/tkinter.ttk.html](https://docs.python.org/zh-cn/3.11/library/tkinter.ttk.html)

![图片](https://github.com/python/python-docs-zh-cn/assets/137136070/252cd697-98cf-44a4-9506-f2a4d63e722e)

抖带 -> 都带

**Comment by silkriver** [comment]
fixed
