### ISSUE TITLE
Exception下的翻译问题

### ISSUE THREAD

**Issue by NoMoCol** [python/python-docs-zh-cn#32]
https://docs.python.org/zh-cn/3/library/exceptions.html#Exception
“所有内置的非系统退出类异常都派生自此类。 所有用户自定义异常也应当**没打算**自此类。“
应该是
“所有内置的非系统退出类异常都派生自此类。 所有用户自定义异常也应当**派生**自此类。“

**Comment by silkriver** [comment]
thx, fixed
