### ISSUE TITLE
[Typo]: 《Unicode 指南》一处笔误

### ISSUE THREAD

**Issue by HairlessVillager** [python/python-docs-zh-cn#326]
### Python Version

3.11.5

### Docs Page

https://docs.python.org/zh-cn/3/howto/unicode.html

### Original Translation

ASCII 字符串也是也是也是合法的 UTF-8 文本。

### Original Docs Paragraph

A string of ASCII text is also valid UTF-8 text.

### Suggested Fix

ASCII 字符串也是合法的 UTF-8 文本。

**Comment by WendaoLee** [comment]
Fixed
