### ISSUE TITLE
[Typo]: 《Python常见问题》一处牛头不对马嘴的翻译

### ISSUE THREAD

**Issue by HairlessVillager** [python/python-docs-zh-cn#327]
### Python Version

3.11.5

### Docs Page

https://docs.python.org/zh-cn/3/faq/general.html#is-python-a-good-language-for-beginning-programmers

### Original Translation

Python 是一种对编程初学者友好的语言吗？

有的。

### Original Docs Paragraph

Is Python a good language for beginning programmers?

Yes.

### Suggested Fix

Python 是一种对编程初学者友好的语言吗？

是的。

**Comment by WendaoLee** [comment]
Fixed
