### ISSUE TITLE
有个条目会被反复修改，请 Reviewer 审核此条目锁定修改

### ISSUE THREAD

**Issue by silkriver** [python/python-docs-zh-cn#328]
在3.8-3.11的c-api--sys中有一个条目的翻译每周五都会被修改为旧译文（可能是自动复制译文的脚本做的），并导致同步报错

复制以下文本查找条目，历史记录已经有几十条了……
```
Raises an :ref:`auditing event <auditing>` ``sys.addaudithook`` with no arguments.
```

**Comment by silkriver** [comment]
好像还没有复核（词条前的绿点应变为蓝勾）

**Comment by BlueGlassBlock** [comment]
应该是 https://github.com/rffontenelle/python-docs-tx-translations 的脚本自动从 python-newest 拉取更改并同步到 3.11 及以下，这个操作会先取消复核再覆盖翻译。奇怪的是为什么它不使用 python-newest 中的译文......

**Comment by silkriver** [comment]
3.11以下又被改了，请换个做法试试：取消3.12中条目的复核并将词句修改一下，看下周其他版本会不会用新译文覆盖……

**Comment by BlueGlassBlock** [comment]
我将译文修改为 <code>引发 :ref:`审计事件 <auditing>` ``sys.addaudithook``，不附带任何参数。</code> 了，应该对语义没有影响。

**Comment by silkriver** [comment]
发现问题出在library--sys中，那里有一个同样的条目，如果翻成中文就会报错，如果直接复制英文内容则没有问题。需要继续研究……

**Comment by Dumeng** [comment]
These two strings do not really exist in the docs. 

https://github.com/python/cpython/blob/3e6b32875207c39325ed8eded5819cfa5dcebc82/Doc/c-api/sys.rst?plain=1#L393

https://github.com/python/cpython/blob/3e6b32875207c39325ed8eded5819cfa5dcebc82/Doc/library/sys.rst?plain=1#L47

Just putting a space as a placeholder will resolve the issue.
