### ISSUE TITLE
[Typo]: 《pdb --- Python 的调试器》一处笔误

### ISSUE THREAD

**Issue by somata-cn** [python/python-docs-zh-cn#330]
### Python Version

3

### Docs Page

https://docs.python.org/zh-cn/3/library/pdb.html#pdbcommand-where

### Original Translation

w(here)
抢鲜栈回溯，最新的帧位于底部。 有一个箭头 (>) 指明当前帧，该帧决定了大多数命令的上下文。

### Original Docs Paragraph

w(here)
Print a stack trace, with the most recent frame at the bottom. An arrow (>) indicates the current frame, which determines the context of most commands.

### Suggested Fix

w(here)
打印栈回溯，最新的帧位于底部。 有一个箭头 (>) 指明当前帧，该帧决定了大多数命令的上下文。

**Comment by silkriver** [comment]
fixed
