### ISSUE TITLE
[Typo]: 《Python 速览》中分号应该为冒号，原文理解起来很奇怪，前后文一对比才明白。并且应增加“类型”以避免歧义

### ISSUE THREAD

**Issue by Leo-Mu** [python/python-docs-zh-cn#331]
### Python Version

3.12

### Docs Page

https://docs.python.org/zh-cn/3/tutorial/introduction.html#first-steps-towards-programming

### Original Translation

[while](https://docs.python.org/zh-cn/3/reference/compound_stmts.html#while) 循环只要条件（这里是 a < 10）为真就会一直执行。Python 和 C 一样，任何非零整数都为真，零为假。这个条件也可以是字符串或列表的值，事实上，任何序列都可以；长度非零就为真，空序列则为假。

### Original Docs Paragraph

The [while](https://docs.python.org/3/reference/compound_stmts.html#while) loop executes as long as the condition (here: a < 10) remains true. In Python, like in C, any non-zero integer value is true; zero is false. The condition may also be a string or list value, in fact any sequence; anything with a non-zero length is true, empty sequences are false.

事实上原文在这里貌似就有问题，其中两个分号的意义是不一样的，这不利于理解同时也不合理。这是否要先给英文文档提 issue？

### Suggested Fix

[while](https://docs.python.org/zh-cn/3/reference/compound_stmts.html#while) 循环只要条件（这里是 a < 10）为真就会一直执行。Python 和 C 一样，任何非零整数都为真，零为假。这个条件也可以是字符串或列表类型的值，事实上，任何序列都可以：长度非零就为真，空序列则为假。

**Comment by silkriver** [comment]
fixed
