### ISSUE TITLE
[Typo]: IO模块性能翻译错误

### ISSUE THREAD

**Issue by Aprilerr** [python/python-docs-zh-cn#332]
### Python Version

3.12

### Docs Page

https://docs.python.org/zh-cn/3/library/io.html#id3

### Original Translation

文本 I/O
二进制存储（如文件）上的文本 I/O 比同一存储上的文本 I/O 慢得多

### Original Docs Paragraph

Text I/O
Text I/O over a binary storage (such as a file) is significantly slower than binary I/O over the same storage,

### Suggested Fix

文本 I/O
二进制存储（如文件）上的文本 I/O 比同一存储上的二进制 I/O 慢得多

**Comment by silkriver** [comment]
fixed
