### ISSUE TITLE
[Typo]: pow()文档翻译

### ISSUE THREAD

**Issue by a48zhang** [python/python-docs-zh-cn#334]
### Python Version

3.12

### Docs Page

https://docs.python.org/zh-cn/3/library/functions.html#pow

### Original Translation

对于 [int](https://docs.python.org/zh-cn/3/library/functions.html#int) 或 [float](https://docs.python.org/zh-cn/3/library/functions.html#float) 类型的负基和一个非整数的指数，会产生一个复杂的结果。

### Original Docs Paragraph

For a negative base of type [int](https://docs.python.org/3/library/functions.html#int) or [float](https://docs.python.org/3/library/functions.html#float) and a non-integral exponent, a complex result is delivered.

### Suggested Fix

对于 [int](https://docs.python.org/zh-cn/3/library/functions.html#int) 或 [float](https://docs.python.org/zh-cn/3/library/functions.html#float) 类型的负基和一个非整数的指数，会产生一个复数。

**Comment by WendaoLee** [comment]
Fixed.
