### ISSUE TITLE
[Typo]: 多余的未翻译文本

### ISSUE THREAD

**Issue by HairlessVillager** [python/python-docs-zh-cn#336]
### Python Version

3.12, 3.11.6, 3.10.13

### Docs Page

https://docs.python.org/zh-cn/3/reference/datamodel.html

### Original Translation

如果一个类没有定义 [__eq__()](https://docs.python.org/zh-cn/3/reference/datamodel.html#object.__eq__) 方法那么它也不应该定义 [__hash__()](https://docs.python.org/zh-cn/3/reference/datamodel.html#object.__hash__) 操作；如果它定义了 [__eq__()](https://docs.python.org/zh-cn/3/reference/datamodel.html#object.__eq__) 但没有定义 [__hash__()](https://docs.python.org/zh-cn/3/reference/datamodel.html#object.__hash__)，则其实例将不可被用作可哈希多项集的条目。 如果一个类定义了可变对象并实现了 [__eq__()](https://docs.python.org/zh-cn/3/reference/datamodel.html#object.__eq__) 方法，则它不应该实现 [__hash__()](https://docs.python.org/zh-cn/3/reference/datamodel.html#object.__hash__)，因为 [hashable](https://docs.python.org/zh-cn/3/glossary.html#term-hashable) 多项集的实现要求键的哈希值是不可变的（如果对象的哈希值发生改变，它将位于错误的哈希桶中）。 hash bucket).

### Original Docs Paragraph

If a class does not define an [__eq__()](https://docs.python.org/3/reference/datamodel.html#object.__eq__) method it should not define a [__hash__()](https://docs.python.org/3/reference/datamodel.html#object.__hash__) operation either; if it defines [__eq__()](https://docs.python.org/3/reference/datamodel.html#object.__eq__) but not [__hash__()](https://docs.python.org/3/reference/datamodel.html#object.__hash__), its instances will not be usable as items in hashable collections. If a class defines mutable objects and implements an [__eq__()](https://docs.python.org/3/reference/datamodel.html#object.__eq__) method, it should not implement [__hash__()](https://docs.python.org/3/reference/datamodel.html#object.__hash__), since the implementation of [hashable](https://docs.python.org/3/glossary.html#term-hashable) collections requires that a key’s hash value is immutable (if the object’s hash value changes, it will be in the wrong hash bucket).

### Suggested Fix

如果一个类没有定义 [__eq__()](https://docs.python.org/zh-cn/3/reference/datamodel.html#object.__eq__) 方法那么它也不应该定义 [__hash__()](https://docs.python.org/zh-cn/3/reference/datamodel.html#object.__hash__) 操作；如果它定义了 [__eq__()](https://docs.python.org/zh-cn/3/reference/datamodel.html#object.__eq__) 但没有定义 [__hash__()](https://docs.python.org/zh-cn/3/reference/datamodel.html#object.__hash__)，则其实例将不可被用作可哈希多项集的条目。 如果一个类定义了可变对象并实现了 [__eq__()](https://docs.python.org/zh-cn/3/reference/datamodel.html#object.__eq__) 方法，则它不应该实现 [__hash__()](https://docs.python.org/zh-cn/3/reference/datamodel.html#object.__hash__)，因为 [hashable](https://docs.python.org/zh-cn/3/glossary.html#term-hashable) 多项集的实现要求键的哈希值是不可变的（如果对象的哈希值发生改变，它将位于错误的哈希桶中）。

**Comment by WendaoLee** [comment]
Fixed.
