### ISSUE TITLE
[Typo]: Typo in howto/annotation.html

### ISSUE THREAD

**Issue by ice-tong** [python/python-docs-zh-cn#337]
### Python Version

3.12

### Docs Page

https://docs.python.org/zh-cn/3.13/howto/annotations.html

### Original Translation

None

### Suggested Fix

需要移除如下红框中多余的 " ` " 符号
![image](https://github.com/python/python-docs-zh-cn/assets/32220263/ac3f93aa-b0b3-4aea-8012-333ac8207fcf)

**Comment by WendaoLee** [comment]
Fixed.

**Comment by ice-tong** [comment]
Nice work!

**Comment by ice-tong** [comment]
所有版本的译文都有这个问题，但貌似只修复了 3.1？

**Comment by WendaoLee** [comment]
> @WendaoLee 所有版本的译文都有这个问题，但貌似只修复了 3.12 ？

昨天我只订正了3.12的，没有检查其他版本的，抱歉。待我晚上回去检查一下。

**Comment by WendaoLee** [comment]
> > @WendaoLee 所有版本的译文都有这个问题，但貌似只修复了 3.12 ？
> 
> 昨天我只订正了3.12的，没有检查其他版本的，抱歉。待我晚上回去检查一下。

事实上昨天 @silkriver 就已经弥补我的疏漏把其他版本（这篇指南从3.10、3.11加入）的译文订正了（感谢 :) ）。但好像是因为文档同步的原因所以有延迟：
<img width="276" alt="屏幕截图 2023-11-28 202210" src="https://github.com/python/python-docs-zh-cn/assets/39958730/471a9ce0-c3b3-4ca4-89c6-fcc9d1141e96">

应该等下一次同步就正常了。

但我不太清楚从Transifex上同步的流程机制。虽然这边CI是每小时同步一次，但好像有一些文档的更新似乎是按月进行同步的？这方面的问题可能要请教 @zhsj @BlueGlassBlock @Dumeng  了。

**Comment by zhsj** [comment]
跟新的机制在 https://github.com/python/python-docs-zh-cn/wiki/UpdateProcedure 这里有说明。

**Comment by ice-tong** [comment]
目前看起来这个问题在各 Python 版本的译文中都已经被修复了，感谢你们的工作！
