### ISSUE TITLE
[Typo]: 

### ISSUE THREAD

**Issue by Independent-X** [python/python-docs-zh-cn#341]
### Python Version

3.12

### Docs Page

https://docs.python.org/zh-cn/3.12/library/codecs.html#error-handlers

### Original Translation

![YKA(CHMF6UB L1{72X`Z( Q](https://github.com/python/python-docs-zh-cn/assets/58306791/390f5d57-0080-4b9a-a882-1838e6934fb4)

### Original Docs Paragraph

![JG%FDH@ZS3DL4VO3%7G`RFN](https://github.com/python/python-docs-zh-cn/assets/58306791/05e7a2ac-f48d-4e2a-8a29-0498d1881e22)

### Suggested Fix

将其中的 `:samp:\x{hh}` 改为正确的 `\xhh` 。

**Comment by silkriver** [comment]
fixed
