### ISSUE TITLE
[Typo]: 

### ISSUE THREAD

**Issue by Independent-X** [python/python-docs-zh-cn#342]
### Python Version

3.12

### Docs Page

https://docs.python.org/zh-cn/3.12/library/shutil.html#shutil.copyfileobj

### Original Translation

将**文件类对象** fsrc 的内容拷贝到**文件类对象** fdst。

### Original Docs Paragraph

Copy the contents of the **file-like object** fsrc to the **file-like object** fdst.

### Suggested Fix

我的改进方案：

> 「文件类对象」应改为英文原文「file-like object」或「文件型对象」。因为在[对应的术语对照表](https://docs.python.org/zh-cn/3/glossary.html#term-file-like-object)中，使用的是：「file-like object -- 文件型对象」，而非「文件类对象」。
> 
> 并且，应当添加一个对术语对照表的链接。英文原文没有这个链接导致了一些[阅读问题](https://stackoverflow.com/questions/4359495/what-is-exactly-a-file-like-object-in-python)。

**Comment by silkriver** [comment]
翻译已修改，原文没加链接译文还是先不加了
