### ISSUE TITLE
[Typo]: unittest 中的笔误

### ISSUE THREAD

**Issue by zyf722** [python/python-docs-zh-cn#345]
### Python Version

3

### Docs Page

https://docs.python.org/zh-cn/3/library/unittest.html#load-tests-protocol

### Original Translation

如果你希望在基类上的 `setUpClass` 和 `tearDownClass` 被调用则你必须自己**云**调用它们。

### Original Docs Paragraph

If you want the `setUpClass` and `tearDownClass` on base classes called then you must call up to them yourself.

### Suggested Fix

如果你希望在基类上的 `setUpClass` 和 `tearDownClass` 被调用则你必须自己调用它们。

**Comment by silkriver** [comment]
fixed
