### ISSUE TITLE
[Typo]: "使用 C 或 C++ 扩展 Python" 中的多余内容

### ISSUE THREAD

**Issue by AlexLin625** [python/python-docs-zh-cn#346]
### Python Version

3.10.13

### Docs Page

https://docs.python.org/zh-cn/3.10/extending/extending.html#the-module-s-method-table-and-initialization-function

### Original Translation

更多关于模块的现实的例子包含在Python源码包的 Modules/xxmodule.c 中。这些文件可以用作你的代码模板，或者学习。`脚本 modulator.py 包含在源码发行版或Windows安装中，提供了一个简单的GUI，用来声明需要实现的函数和对象，并且可以生成供填入的模板。脚本在 Tools/modulator/ 目录。查看README以了解用法。`

### Original Docs Paragraph

A more substantial example module is included in the Python source distribution as Modules/xxmodule.c. This file may be used as a template or simply read as an example.

### Suggested Fix

modulator工具似乎在十多年前就从源码中移除。建议删除过时的描述。

> 更多关于模块的现实的例子包含在Python源码包的 Modules/xxmodule.c 中。这些文件可以用作你的代码模板，或者学习。

**Comment by silkriver** [comment]
fixed
