### ISSUE TITLE
[Typo]: 每解释器GIL

### ISSUE THREAD

**Issue by gmdzy2010** [python/python-docs-zh-cn#347]
### Python Version

3.12.2

### Docs Page

https://docs.python.org/zh-cn/3.12/whatsnew/3.12.html

### Original Translation

[PEP 684](https://docs.python.org/zh-cn/3.12/whatsnew/3.12.html#whatsnew312-pep684)，解释器级的单独 [GIL](https://docs.python.org/zh-cn/3.12/glossary.html#term-global-interpreter-lock)

### Suggested Fix

这里的Per的含义是不可以丢的。

- `PEP684`没有实现之前，GIL本身就存在于解释器级别，GIL从诞生之初一直如此。
- `PEP684`核心是`每解释器GIL`，将部分变量上移至VM runtime 的global state，然后让每个子解释器都持有自己的GIL，`Per/每`是这份 PEP 最关键的部分。

举个例子，`Per-CPU variable`准确翻译是`每CPU变量`

结论：`Per-Interpreter GIL` 准确的翻译是直译`每解释器GIL`

另外申请一下翻译员: gmdzy2023

**Comment by silkriver** [comment]
fixed
