### ISSUE TITLE
[Typo]: handler 的翻译问题

### ISSUE THREAD

**Issue by zyf722** [python/python-docs-zh-cn#348]
### Python Version

3

### Docs Page

https://docs.python.org/zh-cn/3/search.html?q=%E5%A4%84%E7%90%86%E5%8F%A5%E6%9F%84

### Original Translation

处理句柄
句柄

### Original Docs Paragraph

Handler
Handle

### Suggested Fix

处理程序 / 处理器
句柄

---

目前译文中存在多处“处理句柄”这类误将 Handler（处理器）与 Handle 的另一义项（句柄，_特指_ 对象或者项目的标识符）混淆的情况，且考虑到“句柄”一词本身就是 handle 在编译器语境里的译文的扩大化、难以直观理解，建议改译作目前译文中同样存在的“处理程序”或者“处理器”。

**Comment by silkriver** [comment]
可以统一翻译为处理器，我改了glossary，大家可以慢慢改掉

**Comment by Dumeng** [comment]
建议使用“处理程序”。“处理器”一词在特定上下文中可能存在歧义。

**Comment by silkriver** [comment]
比如 encoding error handler 就是 'strict' / 'ignore' / 'replace' 这些感觉还是称为错误处理器更合适点
