### ISSUE TITLE
[Typo]: faq/design 中的翻译问题

### ISSUE THREAD

**Issue by frankpfan** [python/python-docs-zh-cn#349]
### Python Version

3.12

### Docs Page

https://docs.python.org/zh-cn/3/faq/design.html

### Original Translation

#id15 中 
与其他语言中添加功能的lambda表单不同

#id28 中
with语言

### Original Docs Paragraph

In #id15 
Unlike lambda forms in other languages, where they add functionality...

In #id28 
Python has a with statment that...

### Suggested Fix

#id15
与其他语言中带来实际功能的 lambda 形式不同
（“表单”应改为“形式”，同时 lambda 两边应带空格）

#id28
with 语句
（语言改为语句，两边带空格）

------

还有一些地方，中文与西文、中文与数字间没有空格，不再赘述。这里加空格是必要的。这一点可能需要在中文文档内整体修改。

**Comment by silkriver** [comment]
fixed
