### ISSUE TITLE
[Typo]: threading 模块事件对象翻译错误

### ISSUE THREAD

**Issue by drsanwujiang** [python/python-docs-zh-cn#351]
### Python Version

3.12

### Docs Page

https://docs.python.org/zh-cn/3/library/threading.html#event-objects

### Original Translation

> 在 3.1 版本发生变更: 很明显，方法总是返回 None。

### Original Docs Paragraph

> Changed in version 3.1: Previously, the method always returned None.

### Suggested Fix

英文使用的是previously，参考翻译：

> 在 3.1 版本发生变更: 在此之前，方法总是返回 None。

**Comment by silkriver** [comment]
fixed
