### ISSUE TITLE
保存时变量消失

### ISSUE THREAD

**Issue by Unknownuserfrommars** [python/python-docs-zh-cn#352]
![image](https://github.com/python/python-docs-zh-cn/assets/163658509/993e1583-6b2a-41e0-aadf-13bef565be61)
这个变量在我保存的时候会消失（就是我crtl+alt+1后，保存时变量前面的“1”不见了，然后弹出了错误警告），多次尝试无效，请问怎么办？
（https://app.transifex.com/python-doc/python-312/translate/#zh_CN/whatsnew--2_0/492281185 ）

**Comment by WendaoLee** [comment]
请检查一下前后方有没有缺失空格 || 在右侧检查一下翻译保存记录，看看是否正确保存了。

**Comment by Unknownuserfrommars** [comment]
> 请检查一下前后方有没有缺失空格 || 在右侧检查一下翻译保存记录，看看是否正确保存了。

添加空格后问题仍然存在 || 问题就是在保存的时候transifex会把我的变量搞消失

**Comment by WendaoLee** [comment]
> > 请检查一下前后方有没有缺失空格 || 在右侧检查一下翻译保存记录，看看是否正确保存了。
> 
> 添加空格后问题仍然存在 || 问题就是在保存的时候transifex会把我的变量搞消失

我还在外面。下午回家的时候看一下。

你可以尝试在资源里下载翻译源文件的po档，对比一下原文的格式是怎么写的。一般来说应该这是标记语法没写对导致的。🤔

**Comment by silkriver** [comment]
可以在页面右上角按钮点“编辑器偏好设置”，选择“启用原始编辑器模式”。默认显示模式有时是有问题。

具体到这个条目译文中每个`符号两边都需要保留空格

**Comment by WendaoLee** [comment]
主要问题就在前面缺少空格（如 silkriver 所说，缺少分隔符）：
![屏幕截图 2024-05-26 172128](https://github.com/python/python-docs-zh-cn/assets/39958730/b1098b8a-79ff-4fa5-a52f-52f62ffd548e)
![image](https://github.com/python/python-docs-zh-cn/assets/39958730/78538aae-f1c5-4acd-9a0d-33303859f834)


可通过右上角的键盘偏好：
![image](https://github.com/python/python-docs-zh-cn/assets/39958730/95518d68-467d-4640-b65d-b13521152c9a)
使用原始模式进行之后的编辑，这样子可以看清空格：
![image](https://github.com/python/python-docs-zh-cn/assets/39958730/667d2b3a-5f4b-43ad-b870-ae1e45bfc7c6)

（其实我挺想吐槽 transifex 的网页编辑器的，容易看不清。所以我个人比较喜欢下载 po 档进行编辑。

**Comment by Unknownuserfrommars** [comment]
好的，谢谢
