### ISSUE TITLE
[Typo]: 函数返回值的翻译错误

### ISSUE THREAD

**Issue by davidsram** [python/python-docs-zh-cn#353]
### Python Version

3.12

### Docs Page

https://docs.python.org/zh-cn/3/tutorial/controlflow.html

### Original Translation

事实上，没有 return语句的函数也返回值，只不过这个值比较是 None （是一个内置名称）

### Original Docs Paragraph

 In fact, even functions without a return statement do return a value, albeit a rather boring one. This value is called None (it’s a built-in name). 

### Suggested Fix

事实上，即使没有返回语句的函数也会返回一个值，尽管这个值可能相当无聊。这个值被称为 None（它是一个内置名称）。

**Comment by WendaoLee** [comment]
fixed
