### ISSUE TITLE
[Type]: 环境变量 PYTHONDUMPREFS 的简介翻译错误

### ISSUE THREAD

**Issue by Hazelmeow** [python/python-docs-zh-cn#354]
### Python Version

3.12

### Docs Page

https://docs.python.org/zh-cn/3.12/using/cmdline.html#envvar-PYTHONDUMPREFS

### Original Translation

如果设置，Python在关闭解释器，及转储对象和引用计数后仍将保持活动。

### Original Docs Paragraph

If set, Python will dump objects and reference counts still alive after shutting down the interpreter.

### Suggested Fix

如果设置，Python 将在关闭解释器后转储仍存活的对象和引用计数。

**Comment by WendaoLee** [comment]
Fixed.✨
