### ISSUE TITLE
[Typo]: 语法错误

### ISSUE THREAD

**Issue by jackwolfey** [python/python-docs-zh-cn#355]
### Python Version

3.7-3.12

### Docs Page

https://docs.python.org/zh-cn/3.11/library/multiprocessing.html#multiprocessing.pool.Pool.map

### Original Translation

可以将 chunksize 设置为一个正整数从而（近似）指定每个块的大小可以。

### Original Docs Paragraph

The (approximate) size of these chunks can be specified by setting chunksize to a positive integer.

### Suggested Fix

可以将 chunksize 设置为一个正整数来指定每个块的（近似）大小。

**Comment by silkriver** [comment]
fixed
