### ISSUE TITLE
请问：如何构建docset格式离线使用（或者生成intersphinx-based结构）？

### ISSUE THREAD

**Issue by edr1412** [python/python-docs-zh-cn#360]
大家好。由于没有找到离线可用的python中文文档（docset）格式，我想利用这个仓库自己生成一个，但是没有成功。

经过我的尝试，英文版文档可以依照 https://devguide.python.org/documentation/start-documenting/ 的方法转换为docset格式（用于Dash, Zeal），

<details>

<summary>我所用的步骤</summary>

1. 下载 https://github.com/python/cpython
2. 在 Doc 目录执行

```
make venv
source venv/bin/activate
python -m pip install --upgrade -r requirements.txt
python -m sphinx -b html . build/html
```

3. 安装[doc2dash](https://github.com/hynek/doc2dash)，执行
```
doc2dash build/html
```

</details>

但是，此中文文档仓库的结构不一样，这不是rst文件而是po文件，无法照搬上述步骤。所以想问下有办法生成python中文文档的docset文件吗？

简单来说，只要能有办法生成 [intersphinx-compatible](https://doc2dash.hynek.me/en/stable/formats/) 文档格式就可以了。

因为我不太了解这些文档格式，如果上述我说的有错误，或者有其他仓库更适合生成docset文件，还望指点。谢谢！

**Comment by Dumeng** [comment]
你的方法是正确的，但需要把翻译文件添加到目录里在构建。

1. 把所有的 `.po` 文件添加到 `Doc` 目录中的 `locales/zh_CN/LC_MESSAGES` 目录下
2. 在 `sphinx-build` 命令中添加 `-D language=zh_CN` 构建参数

请参考 [build.sh](https://github.com/python/python-docs-zh-cn/blob/master/.github/scripts/build.sh)

**Comment by edr1412** [comment]
> 你的方法是正确的，但需要把翻译文件添加到目录里在构建。
> 
> 1. 把所有的 `.po` 文件添加到 `Doc` 目录中的 `locales/zh_CN/LC_MESSAGES` 目录下
> 2. 在 `sphinx-build` 命令中添加 `-D language=zh_CN` 构建参数
> 
> 请参考 [build.sh](https://github.com/python/python-docs-zh-cn/blob/master/.github/scripts/build.sh)

非常感谢，已解决。
