### ISSUE TITLE
[Typo]: interpreter 的翻译问题

### ISSUE THREAD

**Issue by wodray** [python/python-docs-zh-cn#361]
### Python Version

3.10 - 3.13

### Docs Page

https://docs.python.org/zh-cn/3.13/tutorial/modules.html#standard-modules

### Original Translation

编译器

### Original Docs Paragraph

interpreter

### Suggested Fix

解释器

> interpreter 应统一翻译为解释器

**Comment by silkriver** [comment]
fixed
