### ISSUE TITLE
所有版本同步出错

### ISSUE THREAD

**Issue by silkriver** [python/python-docs-zh-cn#366]
### Python Version

all

### Docs Page

https://docs.python.org/zh-cn/3/

### Original Translation

持续40日

### Suggested Fix

需要更新

**Comment by m-aciek** [comment]
`--break-system-packages` flag was added in [pip 23.0.1](https://pip.pypa.io/en/stable/news/#v23-0-1). It looks like the workflow jobs uses some earlier pip version.

https://github.com/python/python-docs-zh-cn/blob/master/.github/scripts/build.sh#L17

**Comment by Dumeng** [comment]
fixed in ac84487938688e71d42f5b64b431d866a453ebe4
