### ISSUE TITLE
transifex 上面找不到3.7版的资源

### ISSUE THREAD

**Issue by 1lin24** [python/python-docs-zh-cn#37]
问个入门级的问题：

transifex 上面找不到Python 3.7 和3.8版的资源。

是否 没有标的那一项就是3.7,那么3.8的入口在哪里

**Comment by silkriver** [comment]
python-newest就是3.7，看来不能翻译3.8，大概因为3.8条目会经常改变
https://www.transifex.com/python-doc/python-newest/translate/#zh_CN/

**Comment by 1lin24** [comment]
> python-newest就是3.7，看来不能翻译3.8，大概因为3.8条目会经常改变
> https://www.transifex.com/python-doc/python-newest/translate/#zh_CN/

好的，谢谢您

**Comment by zhsj** [comment]
3.8正式发布之后才会开始翻译。
