### ISSUE TITLE
参与两天后的3个小建议

### ISSUE THREAD

**Issue by 1lin24** [python/python-docs-zh-cn#39]
感谢这个组织让我有机会参与到中文文档的翻译工作，我原来计划今年开始自己翻译，再分享给需要的朋友，昨天发现这个项目之后，第一时间参与了进来，经过昨天和今天两天的翻译工作，我有以下3个建议：

1. 是否使用协作工具（我愿意负责提供免费的足够满足所有人参与的工具）来协调每个人翻译，尽量每一个篇有一个人完整翻译，以保证同一稿里面的语言风格和词汇翻译统一（因为不是所有人都会主动添加关键词）
2. 是否从组织参与翻译的人，集中力量从某个版本翻译起，然后再各自将自己翻译的成果快速同步到其它版本，在提高翻译质量的同时，也能够高效地推进翻译进度
3. 是否可以组建微信群让参与翻译的人一起相互交流讨论

**Comment by silkriver** [comment]
组织者看来认为GitHub足够
我觉得要使用别的工具，那首先也应该是类似与Transifex的协作翻译工具而且功能更强，如果不是一个整体就没什么意义

**Comment by 1lin24** [comment]
> 组织者看来认为现在的模式已经足够了
> 我觉得如果要使用别的工具，那首先也应该是类似Transifex的协作翻译工具而且功能更强，如果不能整合功能就没有什么意义

我目前看到的情况是，所有的翻译工作很多都章节都只是翻译一小部分，或者进度停止，如果可以使用协作工作（如：worktile/teambition/tower)

组织者可以列出每个版本所有章节，使用看看板管理：
1. 我在翻译哪一个章节，自己分配，然后拉到doing
2. 完成后拉到done
3. 如果处于doing的章节太久没有更新，其它人可以加入推进。

**Comment by MakDon** [comment]
> > 组织者看来认为现在的模式已经足够了
> > 我觉得如果要使用别的工具，那首先也应该是类似Transifex的协作翻译工具而且功能更强，如果不能整合功能就没有什么意义
> 
> 我目前看到的情况是，所有的翻译工作很多都章节都只是翻译一小部分，或者进度停止，如果可以使用协作工作（如：worktile/teambition/tower)
> 
> 组织者可以列出每个版本所有章节，使用看看板管理：
> 
> 1. 我在翻译哪一个章节，自己分配，然后拉到doing
> 2. 完成后拉到done
> 3. 如果处于doing的章节太久没有更新，其它人可以加入推进。

第一条“翻译到哪个章节”可以通过最后更新日期看出。如果一章内有词条近几天有更新，即可说明还有人在跟进。
第二条，拉到 done ，窃以为没有必要，在翻译页面即可看到是否翻译完成。
第三条提到的“太久没有更新”，可以在翻译页面选择 Oldest untranslated 排序，即可看到哪些章节没有更新。在章节页面，可以使用“ 翻译与该日之后”筛选查看是否还有人跟进该章节翻译。

现实情况是，每个人都是贡献自己的业余时间参与翻译，一个人可以独立翻译一个章节似乎才是少见情况；而且，让翻译志愿者使用工具会额外花费时间，而似乎并不能带来效率和质量上的收益。
因此，个人认为，并没有使用其它第三方工具的需要。

**Comment by 1lin24** [comment]
> 让翻译志愿者使用工具会额外花费时间

有道理
