### ISSUE TITLE
asyncio底层API翻译错误

### ISSUE THREAD

**Issue by sangyu1996** [python/python-docs-zh-cn#42]
https://docs.python.org/zh-cn/3/library/asyncio-llapi-index.html#event-loop-methods
关闭事件循环应为 loop.close(), 当前为loop.stop()

BTW, 非常感谢各位的付出，给国内的python开发者提供了巨大的便利，大大提高了学习效率。谢谢！

**Comment by MakDon** [comment]
Fixed. 请下次文档自动拉取更新后检查一下是否修正，谢谢。

**Comment by MakDon** [comment]
文档已自动拉取更新，自查没有发现问题，应该可以关 issue 了。
