### ISSUE TITLE
3.7中文翻译，datamodel章节，生成器函数，such a function翻译错误

### ISSUE THREAD

**Issue by neo0801** [python/python-docs-zh-cn#43]
https://docs.python.org/zh-cn/3.7/reference/datamodel.html
生成器函数
一个使用 yield 语句 （见 yield 语句 章节）的函数或方法被称作一个 生成器函数。**_利益个函数_**（英文原文：Such a function），当调用时，总是返回一个可以执行函数体的迭代器对象：调用该迭代器的 iterator.__next__() 方法将会导致这个函数一直运行直到它使用 yield 语句提供了一个值为止。当这个函数执行 return 语句或者最后停止， 一个 StopIteration 异常被抛出并且这个迭代器将会到达将被返回的值的集合的末尾。

**Comment by silkriver** [comment]
fixed
