### ISSUE TITLE
12. 虚拟环境和包

### ISSUE THREAD

**Issue by linsui** [python/python-docs-zh-cn#44]
https://docs.python.org/zh-cn/3/tutorial/venv.html#introduction

> 然后，不同的应用可以使用不同的虚拟环要解决先前的冲突需求示例，应用程序A可以拥有自己的1.0版本安装虚拟环境，而应用程序B则具有2.0版本的另一个虚拟环境。如果应用程序B要求将库升级到3.0版本，也不会影响应用程序A的环境。

如果有 issue 模板就更好了。

**Comment by silkriver** [comment]
fixed
