### ISSUE TITLE
代码中的 is 和 is not 被翻译为了中文

### ISSUE THREAD

**Issue by ivylee0919** [python/python-docs-zh-cn#45]
页面链接： https://docs.python.org/zh-cn/3/library/operator.html#mapping-operators-to-functions

表格中，Syntax 这一列，将 is 和 is not 翻译为 是 和 不是 了，这不是需要翻译的内容，具体参见下图：

![image](https://user-images.githubusercontent.com/11519486/62190053-07001d80-b3a3-11e9-98d4-0a0d3b1b0e6a.png)

**Comment by zhsj** [comment]
fixed
