### ISSUE TITLE
翻译出现错别字

### ISSUE THREAD

**Issue by steven756284184** [python/python-docs-zh-cn#46]
[教程第九章“”类“”的9.3.2节"类对象"](https://docs.python.org/zh-cn/3/tutorial/classes.html#class-objects)
第四段“可以相像类对象就是会返回一个新的类实例的不带参数的函数”中的“相像”应为“想象”。
[原文对照](https://docs.python.org/3/tutorial/classes.html#class-objects)：
"Just pretend that the class object is a parameterless function that returns a new instance of the class."

**Comment by silkriver** [comment]
fixed
