### ISSUE TITLE
Translation mistake

### ISSUE THREAD

**Issue by t4rf9** [python/python-docs-zh-cn#47]
In the Section of "Creating a Socket" from https://docs.python.org/3/howto/sockets.html# , "Finally, the argument to listen tells the socket library that we want it to queue up as many as 5 connect requests (the normal max) before refusing outside connections. If the rest of the code is written properly, that should be plenty." is wrongly translated as "最后，listen 方法的参数会告诉套接字库，我们希望在拒绝外部请求连接前最多使用 5 个连接请求的队列。如果所有的代码都要正确的写出来，代码量将会很大。".
I recommend "最后，listen 方法的参数会告诉套接字库，我们希望在队列中累积多达5个（通常的最大值）连接请求后再拒绝外部连接。如果所有其他代码都准确无误，这个队列长度应该就很充裕了。"

**Comment by silkriver** [comment]
fixed
