### ISSUE TITLE
asyncio.Future 无需翻译

### ISSUE THREAD

**Issue by WokoLiu** [python/python-docs-zh-cn#48]
[asyncio.Future](https://docs.python.org/zh-cn/3/library/asyncio-future.html) 可以直接翻译为 "Future 对象"，没必要也不应该为其创造一个专有名词 “期程”

**Comment by mu2019** [comment]
“期程”是我弄出来的，如果感觉不合适的话可以改回去。这段时间我没时间改了，有空的话可以按你的意思改一下。

**Comment by WokoLiu** [comment]
@mu2019 我在 transifex 里有给你发站内信说明情况，你最近没时间的话，我就直接改了哈

**Comment by WokoLiu** [comment]
自查已经改过来了
