### ISSUE TITLE
reference/simple_stmts翻译错误

### ISSUE THREAD

**Issue by steven756284184** [python/python-docs-zh-cn#49]
[译文](https://docs.python.org/zh-cn/3.7/reference/simple_stmts.html#assignment-statements)：
如果目标为一个切片：性和痛苦的原型表达式会被求值。 
[对应原文](https://docs.python.org/3.7/reference/simple_stmts.html#assignment-statements)：
If the target is a slicing: The primary expression in the reference is evaluated.

**Comment by MakDon** [comment]
翻译得太哲学了以至于我不知道怎么样fix……

**Comment by silkriver** [comment]
手残害死猫……

**Comment by MakDon** [comment]
review 发现@zhsj 在 9 天前已修复此 typo.
@steven756284184 可以关 issue 了。
