### ISSUE TITLE
Transifex 上的默认项目已切换为 Python 3.8

### ISSUE THREAD

**Issue by zhsj** [python/python-docs-zh-cn#50]
https://mail.python.org/pipermail/doc-sig/2019-September/004145.html

**Comment by silkriver** [comment]
3.7的红叉先不管了吧

**Comment by zhsj** [comment]
> 英文默认是3.8了 https://docs.python.org/
> 中文默认还是3.7 https://docs.python.org/zh-cn/
> 需要设置吗

应该会有人统一设置的，https://docs.python.org/fr/3/ 其他语言也还是 3.7

**Comment by zhsj** [comment]
问了下 mdk，并不是他统一一起切换的。。。让他把中文的切到 3.8 了，其他语言没切。缓存失效大概需要 24h。
