### ISSUE TITLE
9.3.4 方法对象翻译模糊

### ISSUE THREAD

**Issue by zi-l** [python/python-docs-zh-cn#51]
`python 3.7.4`

章节： [方法对象](https://docs.python.org/zh-cn/3/tutorial/classes.html#method-objects)

原文
>  If the name denotes a valid class attribute that is a function object, a method object is created by packing (pointers to) the instance object and the function object just found together in an abstract object: this is the method object.

译文
> 如果名称表示一个属于函数对象的有效类属性，会通过合并打包（指向）实例对象和函数对象到一个抽象对象中的方式来创建一个方法对象：这个抽象对象就是方法对象。

以上为方法对象的实现细节说明。

`the name`为特指，这句应翻译为
```
如果被引用的属性名称表示一个有效的类属性中的函数对象
```
`the instance object and the function object` 也是特指，这段话的上一句是 `When a non-data attribute of an instance is referenced, the instance’s class is searched. `  所以这句应该翻译为
```
会通过打包（指向）查找到的实例对象和函数对象到一个抽象对象的方式来创建方法对象：这个抽象对象就是方法对象
```

**Comment by silkriver** [comment]
fixed

**Comment by silkriver** [comment]
我看到文档已经更新了
