### ISSUE TITLE
transifex内容未更新到3.8-staging分支中

### ISSUE THREAD

**Issue by ppcfish** [python/python-docs-zh-cn#52]
是否从 Transifex 拉取最新的翻译到 $version-staging 的分支 出现了问题？
发现有transifex的内容很多天前已更新，但是3.8-staging分支中对应文件未更新：

例如：
https://www.transifex.com/python-doc/python-newest/translate/#zh_CN/using--cmdline  未译数为0
而 https://github.com/python/python-docs-zh-cn/blob/3.8-staging/using/cmdline.po 中，“Raises an”的条目对应的翻译内容都是空白

**Comment by silkriver** [comment]
不知道是什么机制，盯住一个文件翻下去，也许就会更新的

**Comment by ppcfish** [comment]
@zhsj 能否检查下是什么原因？
其他未完全翻译的章节也有类似的情况：第一次翻译的内容会更新到3.8-staging ，后续修改的内容就没有抓取到更新到3.8-staging

**Comment by zhsj** [comment]
之前 travis 的 cron 任务最高频度是一天一次，所以没把更新的脚本放在 travis 上。

现在可以用 github actions 了，这个 cron 任务的频度可以更高。我把从 transifex 更新翻译的任务放到 github actions 上了，频度是一小时一次。

更新任务应该会比之前可靠。

**Comment by silkriver** [comment]
3.8-staging三天没提交了，3.7-staging是一直在提交，但有些错误好像去不掉

**Comment by zhsj** [comment]
> 3.8-staging三天没提交了，3.7-staging是一直在提交，但有些错误好像去不掉

今天改到 GitHub actions 之后，流程改为 从transifex同步 -> build测试 -> 推送到3.8分支。不经过 staging 分支了。

**Comment by silkriver** [comment]
原来是这样~

**Comment by ppcfish** [comment]
嗯，这么久才看到回复，都快要以为管理员弃坑了。
今天翻看了一下，以前没有同步的都更新了，非常感谢

人生苦短，猫生几何。
希望在我的有生之年python-docs-zh-cn能翻译完毕

**Comment by zhsj** [comment]
用 transifex 客户端 pull 翻译时，加了 `--force`，目前看更可靠一些，这个问题先关闭了。
https://github.com/python/python-docs-zh-cn/blob/d499d11/.github/actions/update/entrypoint.sh#L27
