### ISSUE TITLE
排序指南

### ISSUE THREAD

**Issue by jianrongwangtju** [python/python-docs-zh-cn#54]
>>> sorted("This is a test string from Andrew".split(), key=str.lower)
['a', 'Andrew', 'from', 'is', 'string', 'test', 'This']
这个例子无法运行，有错误，需要改正。

**Comment by zhsj** [comment]
你是想说 `sorted("This is a test string from Andrew".split(), key=str.lower)` 这行代码有问题吗？

这行代码是正确的。
