### ISSUE TITLE
错误好像不提示行号了……

### ISSUE THREAD

**Issue by silkriver** [python/python-docs-zh-cn#57]
不知道是哪一行的错误。我搜索了一遍文本应该都是对的
https://github.com/python/python-docs-zh-cn/commit/76451e78b819a3fb3fcd46aee5f61fe12f703458/checks?check_suite_id=278952317

##[error]/home/runner/work/python-docs-zh-cn/python-docs-zh-cn/cpython/Doc/library/functions.rst:: WARNING: inconsistent term references in translated message. original: [], translated: [':ref:`审核事件 <auditing>`']

**Comment by zhsj** [comment]
昨天我发现了，但是也不知道为啥。。

**Comment by zhsj** [comment]
![image](https://user-images.githubusercontent.com/227180/67517496-4f468780-f6d5-11e9-97b6-99c2b795d19c.png)

出错的是这行，原文件里就没行号。没看出来哪里有问题，就先把这行翻译删掉了。
