### ISSUE TITLE
中文文档翻译错误

### ISSUE THREAD

**Issue by KLGJ** [python/python-docs-zh-cn#59]
3.7.5和3.8的`教程->输入输出->更漂亮的输出格式`中的第二个超链接`格式字字符串字面值`应改为`格式化字符串字面值`。

**Comment by zhsj** [comment]
Transifex上已改，等待更新到网站上。

**Comment by KLGJ** [comment]
`教程->类->Python 作用域和命名空间`中以`通常，`开头的那一段中`作为域`应是`作用域`。

**Comment by silkriver** [comment]
fixed

**Comment by KLGJ** [comment]
`语言参考->词法分析->行结构->显式的行拼接`中第一段中`反斜框`应是`反斜杠`。

**Comment by silkriver** [comment]
fixed
