### ISSUE TITLE
docs.python.org 页面显示不正常

### ISSUE THREAD

**Issue by ppcfish** [python/python-docs-zh-cn#60]
timeit章节在9个月前已经翻译完毕（https://www.transifex.com/python-doc/python-newest/translate/#zh_CN/library--timeit/108416153），显示 未翻译数为0
https://github.com/python/python-docs-zh-cn/blob/3.8/library/timeit.po  也是正常的。

但在3.8官方文档（https://docs.python.org/zh-cn/3.8/library/timeit.html）仍全篇都是英文。
奇怪的是该页面在chrome 的页面刷新的一瞬间（F5强制刷新），会短暂的显示为中文，然后又显示为英文
3.7的页面（https://docs.python.org/zh-cn/3.7/library/timeit.html）也是如此

貌似只有3.6的页面（https://docs.python.org/zh-cn/3.6/library/timeit.html）是正常的，不知道什么情况

**Comment by zhsj** [comment]
可能是缓存，可以用 `curl -XPURGE URL` 的方法强行让 CDN 刷新缓存
