### ISSUE TITLE
似乎有漏掉的内容未翻译

### ISSUE THREAD

**Issue by KLGJ** [python/python-docs-zh-cn#61]
`教程->类`中的大部分内容和标题已经翻译了，但文中还有好几处是英文。是不是忘记翻译了？

**Comment by silkriver** [comment]
是原条目有改动后会清空译文（有时就只是错了个标点而已也要整条返工）
或是条目其实在另一文件中还没翻到
或是有新增条目例如3.8新加了海象运算符这样的

**Comment by ppcfish** [comment]
是时候加一个flag了  #新人必踩的坑
