### ISSUE TITLE
imghdr --- 推测图像类型  字打错了

### ISSUE THREAD

**Issue by wgPython** [python/python-docs-zh-cn#64]
链接：https://docs.python.org/zh-cn/3/library/imghdr.html#imghdr.tests
错误位置：第三句话: 如果测试陈工，这个测试函数应当返回一个描述图像类型的字符串，否则返回 None。
修改:（陈工-> 成功）
------
> 然后我希望可以在 imghdr.what(filename, h=None) 方法下面添加一个示例, 读取本地文件,或者远程文件
位置： https://docs.python.org/zh-cn/3/library/imghdr.html#imghdr.what
```python
import imghdr
import requests
url = "https://www.baidu.com/img/bd_logo1.png"
img_res = requests.get(url, stream=True)
file_type = imghdr.what(None, img_res.content)
print(file_type)
```

**Comment by silkriver** [comment]
fixed
