### ISSUE TITLE
Terms not in glossary / build failing

### ISSUE THREAD

**Issue by JulienPalard** [python/python-docs-zh-cn#7]
I wrongly opened this issue on zh-tw because it was failing on zh-tw in the logs, but it looks like sphinx is picking those translations from this repo:

https://github.com/python/python-docs-zh-tw/issues/56

Typically line 1483-1384 of `library/functions.po` you're having: 

    :term:`path-like 对象`

Should be:

    :term:`path-like object`

(Or you should also translate it in glossary, I think both fixes are working).

**Comment by zhsj** [comment]
Actually fixed monthes ago, but forgot to close the issue.
