### ISSUE TITLE
【非翻译问题】官方文档大版本之间的“更新日志”小节有缺失?

### ISSUE THREAD

**Issue by ppcfish** [python/python-docs-zh-cn#78]
【非翻译问题】目前发现一个官方文档每个大版本之间的“更新日志”小节有缺失的情况。大概情况如下：（以下页面都是拉到底，看最下面的更新日志）

https://docs.python.org/zh-cn/3.8/whatsnew/index.html
（更新日志：3.7的  截至到Python 3.7.0 final   而3.7.1--3.7.6中间的都没有了
     |
     |
https://docs.python.org/zh-cn/3.7/whatsnew/index.html 
（更新日志：3.7的 截至到Python 3.7.6 final）
（更新日志：3.6的 截至到Python 3.6.6 final）  而3.6.6--3.6.10中间的都没有了
     |   
     |
https://docs.python.org/zh-cn/3.6/whatsnew/index.html  
（更新日志：3.6的 截至到Python 3.6.10 final）
     |   
     |
....   ....

比如需要查3.6.8的更新情况说明，在最新的3.8版的文档中就没有，必须得切换回3.6版的才行
如果说是模块弃用了，所以高版本的把某些模块文档删除了，但是这个是更新日志啊。
如果说是历史版本只保留主版本（3.7--3.6--3.5），那3.8版的更新日志中还有3.6.6、3.5.4等等存在，有谁知道这到底是个什么情况？ 我的理解是最新版本应该包括所有的啊

**Comment by zhsj** [comment]
英文版也是这样的，这个问题可以去 docs@python.org 讨论。
