### ISSUE TITLE
python3中文文档改进提议  ‘_thread --- 底层多线程 API’ 章节

### ISSUE THREAD

**Issue by trialblazer** [python/python-docs-zh-cn#79]
链接： 
[_thread --- 底层多线程 API  章节](https://docs.python.org/zh-cn/3/library/_thread.html?highlight=_thread#_thread.stack_size)

当前翻译： 返回新建线程是用的堆栈大小。
问题： ‘使用’ 翻译成了 ‘是用’
正确翻译： 返回新建线程使用的堆栈大小。

**Comment by silkriver** [comment]
fixed
