### ISSUE TITLE
翻译错误：Python 标准库 » 并发执行 »threading »线程对象中守护线程标志一句

### ISSUE THREAD

**Issue by 374jetko** [python/python-docs-zh-cn#82]
错误1：
中文为：“一个线程可以被标记成一个 "守护线程" 。这个标志的意义是，只有守护线程都终结，整个Python程序才会退出。”
英文为：“A thread can be flagged as a “daemon thread”. The significance of this flag is that the entire Python program exits when only daemon threads are left. ”
正确翻译应为：“一个线程可以被标记成一个 "守护线程" 。这个标志的意义是，当剩下的（存活）线程都是守护线程时，整个Python程序会退出。”

错误2：
中文为：“如果 daemon 不是 None，线程将被显式的设置为 守护模式，不管该线程是否是守护模式。”
英文为：“If not None, daemon explicitly sets whether the thread is daemonic. ”
正确翻译应为：“如果不是 None，则daemon参数将显式地设置该线程是守护模式或非守护模式。”。或意译“如果不是 None，则该线程的守护模式为True或False将由daemon参数显式地指明。”

3.6到3.9版本的中文翻译都一样，都错了。

**Comment by silkriver** [comment]
fixed
