### ISSUE TITLE
翻译错误：Python 标准库 » 并发执行 »multiprocessing »连接（Connection）对象

### ISSUE THREAD

**Issue by 374jetko** [python/python-docs-zh-cn#84]
https://docs.python.org/zh-cn/3/library/multiprocessing.html#multiprocessing.connection.Connection.recv_bytes
错误1：
中文翻译为：“如果给定了 maxlength  并且消息短于 maxlength  那么将抛出 OSError  并且该连接对象将不再可读。”
英文为：“If maxlength is specified and the message is longer than maxlength then OSError is raised and the connection will no longer be readable.”
正确翻译应为：“如果给定了 maxlength  并且消息长于 maxlength  那么将抛出 OSError  并且该连接对象将不再可读。"

错误2：
中文翻译为：“警告 The Connection.recv() method automatically unpickles the data it receives, which can be a security risk unless you can trust the process which sent the message.
因此， 除非连接对象是由 Pipe()  产生的，在通过一些认证手段之前你应该只使用 recv() 和 send() 方法。参考 认证密码 。”
英文为：“Warning  The Connection.recv() method automatically unpickles the data it receives, which can be a security risk unless you can trust the process which sent the message.
Therefore, unless the connection object was produced using Pipe() you should only use the recv() and send() methods after performing some sort of authentication. See Authentication keys.
”
正确翻译应为：“警告 Connection.recv()方法会自动反序列化它接收到的数据，所以这可能会是个安全风险，除非你能够信任发送消息的进程。因此，除非连接对象是由 Pipe()  产生的，否则你应该仅在使用了某种认证手段之后才使用recv()和send()方法。参考 认证密码 。”

**Comment by silkriver** [comment]
fixed
