### ISSUE TITLE
How to download the CHM file of Chinese translation?

### ISSUE THREAD

**Issue by huanghe2015** [python/python-docs-zh-cn#9]
如题，怎么将在线帮助文档以CHM形式下载下来？？

**Comment by silkriver** [comment]
首页左上角有下载页链接 https://docs.python.org/zh-cn/

**Comment by zhsj** [comment]
没有官方编译好的，不过 sphinx 支持编译成 [CHM](http://www.sphinx-doc.org/en/master/usage/builders/#sphinx.builders.htmlhelp.HTMLHelpBuilder)，可以自己编译。

首先参考 https://github.com/python/python-docs-zh-cn/blob/3.7/build.sh 这个编译脚本，
然后把里面的 `make html SPHINXOPTS=xxx` 改成 `make build BUILDER=htmlhelp SPHINXOPTS=xxx`

**Comment by zhsj** [comment]
又看了下 sphinx 文档，编译完之后是一个包含 html 文件和其他元信息的目录，还要在 Windows 上安装 Microsoft HTML Help Workshop 来生成 CHM 文件。
