### ISSUE TITLE
翻译错误：文档 » Python 标准库 » 数字和数学模块 »statistics.fmean(data)

### ISSUE THREAD

**Issue by laazy** [python/python-docs-zh-cn#94]
- 目标链接：[https://docs.python.org/zh-cn/3.8/library/statistics.html#statistics.fmean](https://docs.python.org/zh-cn/3.8/library/statistics.html#statistics.fmean)
1. 
    - 原始英文：Convert data to floats and compute the arithmetic mean.
    - 原始译文：将**浮点数转换成 data**并且计算算术平均数。
    - 改进翻译：将**data转换为浮点数**并且计算算术平均数。
2. 
    - 原始英文：This runs faster than the mean() function and it always returns a float. The data may be a sequence or iterable. If the input dataset is empty, raises a StatisticsError.
    - 原始译文：此函数的运行速度比 mean() 函数快并且它总是返回一个 float。 data 可以为序列或**迭代器**。 如果输入数据集为空，则会引发 StatisticsError。
    - 改进翻译：此函数的运行速度比 mean() 函数快并且它总是返回一个 float。 data 可以为序列或**可迭代对象**。 如果输入数据集为空，则会引发 StatisticsError。

**Comment by silkriver** [comment]
fixed

**Comment by laazy** [comment]
第二项未修复，**iterable**应翻译为**可迭代对象**，而非**迭代器**。

**Comment by laazy** [comment]
@silkriver

**Comment by silkriver** [comment]
fixed @laazy
