### ISSUE TITLE
翻译错误：文档 » Python 标准库 » 数字和数学模块 »statistics

### ISSUE THREAD

**Issue by sinE0X** [python/python-docs-zh-cn#95]
目标链接：https://docs.python.org/3.9/library/statistics.html#averages-and-measures-of-central-location

1. 
·原始英文：Averages and measures of central location
·原始译文：中心位置的平均值和度量
·改进翻译：平均值以及对中心位置的评估

2. 
·原始英文：These functions calculate an average or typical value from a population or sample.
·原始译文：这些函数计算一个整体或样本的平均值或者特定值。
·改进翻译：这些函数用于计算一个总体或样本的平均值或者典型值。

**Comment by sinE0X** [comment]
> 目标链接：https://docs.python.org/3.9/library/statistics.html#averages-and-measures-of-central-location
> 
> 
> ·原始英文：Averages and measures of central location
> ·原始译文：中心位置的平均值和度量
> ·改进翻译：平均值以及对中心位置的评估
> 
> 
> ·原始英文：These functions calculate an average or typical value from a population or sample.
> ·原始译文：这些函数计算一个**整体**或样本的平均值或者特定值。
> ·改进翻译：这些函数用来计算一个**总体**或样本的平均值或者典型值。

**Comment by silkriver** [comment]
fixed
