### ISSUE TITLE
翻译错误：文档 » Python 标准库 » 数字和数学模块 »statistics

### ISSUE THREAD

**Issue by sinE0X** [python/python-docs-zh-cn#96]
目标链接：https://docs.python.org/zh-cn/3.9/library/statistics.html#measures-of-spread
1. 
·原始英文：Measures of spread
·原始译文：传播措施
·改进翻译：对分散程度的评估

2. 
·原始英文：These functions calculate a measure of how much the population or sample tends to deviate from the typical or average values.
·原始译文：这些函数计算多少总体或者样本偏离典型值或平均值的度量。
·改进翻译：这些函数用于计算总体或样本与典型值或平均值的偏离程度。

**Comment by silkriver** [comment]
fixed
