### ISSUE TITLE
Python3 中文文档 time 模块翻译改进建议

### ISSUE THREAD

**Issue by TRHX** [python/python-docs-zh-cn#99]
【目标链接 (第二段第二句话) 】：https://docs.python.org/zh-cn/3/library/time.html#module-time

【原始英文】：Most of the functions defined in this module call platform C library functions with the same name.

【原始翻译】：此模块中定义的大多数函数调用都具有相同名称的平台C库函数。

【改进建议】：此模块中定义的大多数函数是调用了所在平台C语言库的同名函数。

【改进理由】：语意不清，容易让人错误理解。

**Comment by silkriver** [comment]
fixed
